#+TITLE: Decomposition of transverse isotropic, fourth-rank tensors
#+SETUPFILE: "../../header.org"
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../solarized.css" />

In [[file:../01/elastic-constants-of-isotropic-material.org][a previous post]], I introduced the tensors $\sphprojiv$ and $\devprojiv$ (fourth-rank spherical and deviatoric projection tensors). Any isotropic fourth-rank tensor is a linear combination of these two tensors; in other words, the space of isotropic fourth-rank tensors (with minor and major symmetries) is of dimension 2. Similarly, it can be shown (Walpole, [[file:../../p/references.org::#WALP1984][1984]]) that the space of /transverse isotropic/ fourth-rank tensors (with minor and major symmetries) is of dimension 6. Furthermore, it is possible to produce a convenient basis of this space. This is the topic of the present post, which is mostly based on a paper by Walpole ([[file:../../p/references.org::#WALP1984][1984]]).@@html:<!-- more -->@@$\newcommand{\kronecker}{\circledast}$

* Section

It is recalled that transverse isotropy is defined by one single preferred direction. In the present post, $\vec n$ denotes the unit vector which indicates this preferred direction. Then, $\tensii p$ and $\tensii q$ are the following second-rank projection tensors

\begin{equation*}
\tensii p=\vec n\otimes\vec n,\quad\tensii q=\identii-\tensii p,
\end{equation*}

and it can readily be verified that

\begin{align*}
\tensii p\cdot\tensii p&=\tensii p,&\tensii q\cdot\tensii q&=\tensii q,&\tensii p\cdot\tensii q&=\tensii q\cdot\tensii p=\tensii 0,\\
\tensii p:\tensii p&=1,&\tensii q:\tensii q&=2,&\tensii p:\tensii q&=\tensii q:\tensii p=0.
\end{align*}

* Tensor product of linear transformations

It will be convenient to introduce a new, Kronecker-like product of two second-rank tensors, which Del Piero ([[file:../../p/references.org::#PIER1979][1979]]) named /tensor product of linear transformations/. It is denoted $\boxtimes$.

As a preliminary note, it should be observed that any fourth-rank tensor $\tensiv A$ can be viewed as a endomorphism over the space of second-rank tensors, since $\tensii x\mapsto\tensiv A:\tensii x$ is a linear mapping (the convention adopted in this blog for the double dot product has been specified in a [[file:./on-double-dot-product.org][previous post]]). Therefore, the fourth-rank tensor $\tensii a\boxtimes\tensii b$ ($\tensii a, \tensii b$: second-rank tensors) can be defined by how it operates on second-rank tensors $\tensii x$

\begin{equation}
\label{eq:1}
\left(\tensii a\boxtimes\tensii b\right):\tensii x=\tensii a\cdot\tensii x\cdot\transp{\tensii b}.
\end{equation}

Writing the above definition in terms of the components of $\tensii a$, $\tensii b$ and $\tensii x$, we find $\left(\tensii a\boxtimes\tensii b\right):\tensii x=a_{ik}x_{kl}b_{jl}\vec e_i\otimes\vec e_j$, which shows that the components of $\tensii a\boxtimes\tensii b$ are

\begin{equation}
\label{eq:2}
\left(\tensii a\boxtimes\tensii b\right)_{ijkl}=a_{ik}b_{jl}.
\end{equation}

From the above identity, it is readily found that

\begin{equation}
\label{eq:3}
\transp{\left(\tensii a\boxtimes\tensii b\right)}=\transp{\tensii a}\boxtimes\transp{\tensii b}.
\end{equation}

Given four second-rank tensors $\tensii a$, $\tensii b$, $\tensii c$ and $\tensii d$, we have

\begin{equation}
\label{eq:4}
\left(\tensii a\boxtimes\tensii b\right):\left(\tensii c\boxtimes\tensii d\right)=\left(\tensii a\cdot\tensii c\right)\boxtimes\left(\tensii b\cdot\tensii d\right).
\end{equation}

Indeed, let $\tensii x$ be a second-rank tensor. Then, from Eq. \eqref{eq:1}

\begin{equation*}
\left(\tensii a\boxtimes\tensii b\right):\left(\tensii c\boxtimes\tensii d\right):\tensii x=\left(\tensii a\boxtimes\tensii b\right):\left(\tensii c\cdot\tensii x\cdot\transp{\tensii d}\right)=\tensii a\cdot\left(\tensii c\cdot\tensii x\cdot\transp{\tensii d}\right)\cdot\transp{\tensii b}=\left(\tensii a\cdot\tensii c\right)\cdot\tensii x\cdot\left(\transp{\tensii d}\cdot\transp{\tensii b}\right)=\left(\tensii a\cdot\tensii c\right)\cdot\tensii x\cdot\transp{\left(\tensii b\cdot\tensii d\right)}=\left(\left(\tensii a\cdot\tensii c\right)\boxtimes\left(\tensii b\cdot\tensii d\right)\right):\tensii x.
\end{equation*}


Eq. \eqref{eq:2} shows that even if $\tensii a$ and $\tensii b$ are symmetric, the tensor product $\tensii a\boxtimes\tensii b$ does not necessarily have the minor symmetries. It will therefore be convenient to define $\tensii a\boxtimessym\tensii b$, as the tensor $\tensii a\boxtimes\tensii b$, /symmetrized with respect to the last two indices/

\begin{equation}
\label{eq:5}
\left(\tensii a\boxtimessym\tensii b\right)_{ijkl}=\frac12\left(a_{ik}b_{jl}+a_{il}b_{jk}\right),
\end{equation}

or, in intrinsic form ($\tensii x$: second-rank tensor)

\begin{equation}
\label{eq:6}
\left(\tensii a\boxtimessym\tensii b\right):\tensii x=\frac12\left(\tensii a\boxtimes\tensii b\right):\left(\tensii x+\transp{\tensii x}\right)=\frac12\tensii a:\left(\tensii x+\transp{\tensii x}\right):\transp{\tensii b}.
\end{equation}

An identity similar to Eq. \eqref{eq:4} can be derived with $\boxtimessym$

\begin{equation}
\label{eq:7}
\left(\tensii a\boxtimessym\tensii b\right):\left(\tensii c\boxtimessym\tensii d\right)=\frac12\left(\left(\tensii a\cdot\tensii c\right)\boxtimessym\left(\tensii b\cdot\tensii d\right)+\left(\tensii a\cdot\tensii d\right)\boxtimessym\left(\tensii b\cdot\tensii c\right)\right).

\end{equation}

* Walpole's basis for transverse isotropic tensors

Walpole ([[file:../../p/references.org::#WALP1984][1984]]) shows that any transverse isotropic tensor is a linear combination of the six fourth-rank tensors $\tensiv E_1,\tensiv E_2,\tensiv E_3,\tensiv E_4,\tensiv F,\tensiv G$ defined as follows

\begin{gather*}
\tensiv E_1=\tensii p\otimes\tensii p,\quad\tensiv E_2=\frac12\tensii q\otimes\tensii q,\quad\tensiv E_3=\frac1{\sqrt2}\tensii p\otimes\tensii q,\quad\tensiv E_4=\frac1{\sqrt2}\tensii q\otimes\tensii p\\
\tensiv F=\tensii q\boxtimessym\tensii q-\frac12\tensii q\otimes\tensii q,\quad\tensiv G=\tensii p\boxtimessym\tensii q+\tensii q\boxtimessym\tensii p.
\end{gather*}
