#+TITLE: Tensor product of linear transformations
#+SETUPFILE: "../../header.org"
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../solarized.css" />

It is well-known that the classical tensor product $\otimes$ is a Kronecker product which applies to tensors of any rank, and returns a higher-order tensor. In the present post, I will introduce a new Kronecker product which applies to second-rank tensors, and returns a fourth-rank tensor. This tensor product is involved in e.g. the derivation of the Green operator for strains, for which it allows a purely intrinsic approach. It was defined by e.g. Del Piero ([[file:../../p/references.org::#PIER1979][1979]]), and is denoted by $\boxtimes$.@@html:<!-- more -->@@

As a preliminary note, it should be observed that any fourth-rank tensor $\tensiv A$ can be viewed as a endomorphism over the space of second-rank tensors, since $\tensii x\mapsto\tensiv A:\tensii x$ is a linear mapping. In the previous expression, the double dot product ":" has been defined in a [[file:./on-double-dot-product.org][a previous post]]. Therefore, a fourth-rank tensor can (and will) be defined by how it operates on second-rank tensors. Let $\tensii a$ and $\tensii b$ be two second-rank tensors. Then $\tensii a\boxtimes\tensii b$ is a fourth-rank tensor, defined by ($\tensii x$: second-rank tensor)

\begin{equation}
\label{eq:1}
\left(\tensii a\boxtimes\tensii b\right):\tensii x=\tensii a\cdot\tensii x\cdot\transp{\tensii b}.
\end{equation}

Writing the above definition in terms of the components of $\tensii a$, $\tensii b$ and $\tensii x$, we find $\left(\tensii a\boxtimes\tensii b\right):\tensii x=a_{ik}x_{kl}b_{jl}\vec e_i\otimes\vec e_j$, which shows that the components of $\tensii a\boxtimes\tensii b$ are

\begin{equation}
\label{eq:2}
\left(\tensii a\boxtimes\tensii b\right)_{ijkl}=a_{ik}b_{jl}.
\end{equation}

From the above identity, it is readily found that

\begin{equation}
\label{eq:3}
\transp{\left(\tensii a\boxtimes\tensii b\right)}=\transp{\tensii a}\boxtimes\transp{\tensii b}.
\end{equation}

It can readily be observed from Eq. \eqref{eq:2} that even if $\tensii a$ and $\tensii b$ are symmetric, the tensor product $\tensii a\boxtimes\tensii b$ does not necessarily have the minor symmetries. It will therefore be convenient to define $\tensii a\boxtimessym\tensii b$, as the tensor $\tensii a\boxtimes\tensii b$, /symmetrized with respect to the last two indices/

\begin{equation}
\label{eq:4}
\left(\tensii a\boxtimessym\tensii b\right)_{ijkl}=\frac12\left(a_{ik}b_{jl}+a_{il}b_{jk}\right),
\end{equation}

or, in intrinsic form ($\tensii x$: second-rank tensor)

\begin{equation}
\label{eq:5}
\left(\tensii a\boxtimessym\tensii b\right):\tensii x=\frac12\left(\tensii a\boxtimes\tensii b\right):\left(\tensii x+\transp{\tensii x}\right)=\frac12\tensii a:\left(\tensii x+\transp{\tensii x}\right):\transp{\tensii b}.
\end{equation}

This symmetrized product will be used in the next post of the decomposition of transverse isotropic tensors.
