# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: When a thin shell is not so thin, part\nbsp{}1: Koiter's linear theory
#+DATE: [2015-06-08 Mon]
#+LINK: koit1970 https://www.mathunion.org/fileadmin/ICM/Proceedings/ICM1970.3/ICM1970.3.ocr.pdf

In structural analysis, thick beams (resp. plates) usually refer to shear deformability, and the [[http://en.wikipedia.org/wiki/Timoshenko_beam_theory][Timoshenko beam theory]] (resp. [[http://en.wikipedia.org/wiki/Mindlin%E2%80%93Reissner_plate_theory][Mindlin–Reissner plate theory]]). With curved elements however (e.g. curved beams or shells), the situation is more subtle, as thickness corrections may be necessary even in shells /where the shear stress is null at any point/. In this series, this is illustrated with a spherical pressure vessel, for which the stress resultants and couples are studied. "Easy enough", you probably think: \(N=pR/2\), \(M=0\) and that's the end of it ([[http://en.wikipedia.org/wiki/Pressure_vessel#Stress_in_thin-walled_pressure_vessels][Wikipedia]]). Well, maybe...

In the first part of this series, Koiter's thin shell theory ([[koit1970][Koiter, 1970]][fn:1]) is used to analyse the equilibrium of the spherical pressure vessel. In particular, it is shown that the results deviate slightly from what is expected from the membrane theory.

[fn:1] /Actes du Congrès International des Mathématiciens/, vol. 3, pp. 123–130, 1970

* Description of the problem

We consider a spherical vessel, subjected to an internal pressure \(p\). \(R\) denotes the radius of the midsurface, \(h\) the thickness of the shell, so that the inner and outer radii of the shell are
\begin{align}
R_\text{in}&=R-\frac h2,\\
R_\text{out}&=R+\frac h2.
\end{align}

The problem is solved in spherical coordinates. From symmetry considerations (the problem is fully isotropic), the deflection \(w\) (normal displacement of the midsurface) is constant. Similarly, the strain \(\epsilon_{\alpha\beta}\), the change of curvature \(\kappa_{\alpha\beta}\), the membrane force \(N_{\alpha\beta}\) and the bending moment \(M_{\alpha\beta}\) are all diagonal tensors with constant components

\begin{align}
\label{eq:6}\epsilon_{\theta\theta}&=\epsilon,&\epsilon_{\phi\phi}&=\epsilon,&\epsilon_{\theta\phi}&=0,\\
\label{eq:7}\kappa_{\theta\theta}&=\kappa,&\kappa_{\phi\phi}&=\kappa,&\kappa_{\theta\phi}&=0,\\
N_{\theta\theta}&=N,&N_{\phi\phi}&=N,&N_{\theta\phi}&=0,\\
M_{\theta\theta}&=M,&M_{\phi\phi}&=M,&M_{\theta\phi}&=0,
\end{align}

where \(\epsilon\), \(\kappa\), \(N\) and \(M\) are four scalar constants, which will be determined in the next section by means of Koiter's linear theory of thin shells ([[koit1970][Koiter, 1970]]).

* The thin shell solution

Up to terms which are quadratic in the displacement, the trace of the tensor of membrane strains is equal to the relative variation of surface area of the shell. Therefore

\begin{equation}
\label{eq:2}\epsilon=\frac12\epsilon_{\alpha\alpha}=\frac12\frac{4\pi\left(R+w\right)^2-4\pi R^2}{4\pi R^2}\simeq\frac wR.
\end{equation}

There is no simple geometrical derivation that I know of for the determination of the change of curvature, and you will have to trust me on this [... or use Eq. (3.4) in the paper by Koiter ([[koit1970][1970]])].

\begin{equation}
\label{eq:3}\kappa=-\frac w{R^2}.
\end{equation}

The deflection \(w\) of the shell is found by minimizing its total potential energy \(\Pi=U-V\), where \(U\) denotes the srain energy, and \(V\) denotes the potential of external forces. In Koiter's theory of thin shells, the strain energy \(U\) of the shell is the sum of two contributions: \(U=U_\epsilon+U_\kappa\), with

\begin{align}
U_\epsilon&=\frac12\frac{Eh}{1-\nu^2}\int_{\Sigma}\left(\left(1-\nu\right)\epsilon_{\alpha\beta}\epsilon^{\alpha\beta}+\nu\left(\epsilon_\gamma^\gamma\right)^2\right)\mathrm{d}\Sigma=4\pi R^2\frac{Eh}{1-\nu}\epsilon^2,\\
U_\kappa&=\frac12\frac{Eh^3}{12\left(1-\nu^2\right)}\int_{\Sigma}\left(\left(1-\nu\right)\kappa_{\alpha\beta}\kappa^{\alpha\beta}+\nu\left(\kappa_\gamma^\gamma\right)^2\right)\mathrm{d}\Sigma=4\pi R^2\frac{Eh^3}{12\left(1-\nu\right)}\kappa^2,
\end{align}

where use has been made of Eqs. \eqref{eq:6} and \eqref{eq:7}. The strain energy of the shell therefore reads

\begin{equation}
U=4\pi R^2\frac{Eh}{1-\nu}\left(1+\frac{h^2}{12R^2}\right)\frac{w^2}{R^2},
\end{equation}

while the potential of external loads \(V\) is clearly given by the following expression

\begin{equation}
V=4\pi R^2 pw.
\end{equation}

The total potential energy

\begin{equation}
\frac{\Pi}{4\pi R^2}=\frac{Eh}{1-\nu}\left(1+\frac{h^2}{12R^2}\right)\frac{w^2}{R^2}-pw
\end{equation}

is then minimized with respect to the deflection \(w\), which leads to

\begin{equation}
\label{eq:1}w=\frac{pR^2}{2Eh}\frac{1-\nu}{1+\frac{h^2}{12R^2}}.
\end{equation}

The stress resultants and couples are then retrieved from the constitutive laws. For the stress resultants, we have

\begin{equation}
\label{eq:4}N=N_{\theta\theta}=\frac{Eh}{1-\nu^2}\left(\epsilon_{\theta\theta}+\nu\epsilon_{\phi\phi}\right)=\frac{Eh}{1-\nu^2}\left(1+\nu\right)\epsilon=\frac{Eh}{1-\nu}\epsilon,
\end{equation}

and similarly for the stress couples

\begin{equation}
\label{eq:5}M=\frac{Eh^3}{12\left(1-\nu\right)}\kappa.
\end{equation}

<<Koiter_solution>>Substituting Eqs.\eqref{eq:1}, \eqref{eq:2} and \eqref{eq:3} in Eqs. \eqref{eq:4} and \eqref{eq:5} finally leads to the following expansions

\begin{align}
N &= \frac{pR}2\left(1-\frac{h^2}{12R^2}\right)+\mathcal O\left(\frac{h^4}{R^4}\right),\\
M &= -\frac{ph^2}{24}\left(1-\frac{h^2}{12R^2}\right)+\mathcal O\left(\frac{h^6}{R^6}\right).
\end{align}

This is the first surprise in this series: the stress couple is /not/ null, and the stress resultant differ slightly from the well-known formula \(N=pR/2\) (see [[http://en.wikipedia.org/wiki/Pressure_vessel#Stress_in_thin-walled_pressure_vessels][Wikipedia]]).

Nota: the above-mentioned formula \(N=pR/2\) is called "formule des chaudronniers" (formula of boilermakers?) in French, but I could not find any English translation. If you happen to know the name of this formula, please let me know.

* Conclusion

We started with a very simple shell, which we expected to be in a state of membrane equilibrium. However, using Koiter's linear theory of thin shells, we found that the stress couples, though small, are not null!

So what's wrong with the above analysis? To dig deeper into this problem, we will use its full 3D solution to compute /exact/ values of the stress resultants and couples... which will lead to other exciting findings in the [[file:./20150701-When_a_thin_shell_is_not_so_thin-02.org][next instalment]] of this series!
