# -*- coding: utf-8; fill-column: 79 -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+OPTIONS: ':t
#+TITLE: What is homogenization? Part 2: top-down and bottom-up strategies
#+DATE: [2019-08-20 Tue]


Two strategies can be adopted to carry out homogenization. In the so-called
/top-down/ approach, the effective properties are /measured/ (in a broad
sense). In the example above, we could provide the observer with a set of cards
uniformly coloured with various shades of blue, and ask him to pick the card
which is closest to how the blue sky looks from far off. The alternate,
/bottom-up/ approach is often referred to as /upscaling/. In this approach, the
effective properties are /inferred/ (through a mathematical model) from the
microstructure. In the example above, we could /predict/ the effective blue
shade of the lithograph's sky by some kind of weighted average of the blue
shade of the dots, and the white background.

These two strategies should not be seen as competing, but rather as
complementary approaches to the same problem. While the top-down approach
always delivers the “correct” answer (provided that the experiments are
performed correctly), efficient bottom-up approaches have the ability to be
/predictive/: given the microstructure, the effective properties can be
computed with no need to actually /build/ the microstructure. This is
particularly desirable in an industrial context, where numerical modelling is
gradually supplanting physical testing.

In my research, I preferably resort to bottom-up approaches. The remainder of
this series will therefore be devoted to homogenization through upscaling.

* Conclusion

In this post, we introduced the homogenization concept through a graphical
analogy. We explained that the key ingredient for homogenization to be valid is
separation of scales.

In the next instalment of this series, we will discuss homogenization in the
context of the mechanical properties of heterogeneous materials.
