# -*- coding: utf-8; -*-
#+SETUPFILE: ../include/css-1.org
#+BIND: sb-blog-comments nil
#+TITLE: About me

I am currently a research scientist at [[http://navier.enpc.fr/][Navier laboratory]], [[http://www.ifsttar.fr/][IFSTTAR]] (/Institut Français des Sciences et Techniques du Transport, de l'Aménagement et des Réseaux/, French Institute of Sciences and Technology for Transport, Development and Networks).

* Research interests

  - Theoretical and numerical homogenization of the mechanical properties
  - Characterization by non-destructive techniques (small-angle X-ray scattering, micro-tomography) of heterogeneous materials
  - Simulation of random microstructures
  - Image analysis

* Curriculum

  - sept. 2010 - now :: Research scientist at [[http://www.ifsttar.fr/][IFSTTAR]]. Joined [[http://navier.enpc.fr/][Navier laboratory]] nov. 2011.
  - sept. 2007 - aug. 2010 :: PhD at [[http://www.enpc.fr/][Ecole des Ponts ParisTech]], Paris, France, [[http://navier.enpc.fr/][Navier laboratory]]. /Morphological analysis and numerical homogenization: application to cement paste/ (under the supervision of Pr. Luc Dormieux and Pr. Pierre Levitz).
  - march 2007 - aug. 2007 :: Visiting scholar at the [[http://berkeley.edu/][University of California]], Berkeley, [[http://www.ce.berkeley.edu][Civil and Environmental Engineering]] dept. /Characterization of the orientation of fibers by Digital Laminography in Ultra-High Performance, Fiber Reinforced Concrete/ (under the supervision of Pr. Paulo J. M. Monteiro).
  - sept. 2003 - feb. 2007 :: Bridge engineer at [[http://www.setra.equipement.gouv.fr][Sétra]], Bagneux, France (french highway administration).
  - jul. 2001 - aug. 2002 :: Structural engineer (intern) at [[http://www.arup.com][ARUP]], London, UK.
  - sept. 2000 - aug. 2003 :: M. Eng. in civil engineering at [[http://www.enpc.fr][Ecole des Ponts ParisTech]], Champs-sur-Marne, France
  - sept. 1998 - aug. 2000 :: B. Sc. at [[http://www.polytechnique.fr][Ecole Polytechnique]], Palaiseau, France.

* Teaching

Teaching assistant (since 2003), then Assistant Professor (since 2008) at Ecole des Ponts ParisTech for the following classes

  - Theory of Plates and Shells
  - Structural analysis (until 2012)

* Supervision of Postdoctoral Fellows

  - Michaël BERTIN (mar. 2015 - mar. 2016) :: /Variance Reduction Techniques for the Homogenization of Random Materials/ (co-supervised with: [[https://www.rocq.inria.fr/matherials/spip.php?rubrique5][C. Lebris]] and [[http://navier.enpc.fr/LEGOLL-Frederic][F. Legoll]]). This work has benefited from a French government grant managed by ANR within the frame of the national program Investments for the Future ANR-11-LABX-022-01.
  - Linlin WANG (sept. 2013 - aug. 2014) :: ANHYMA project (hydromechanical couplings within the clay matrix of argilites) (co-supervised with: [[http://navier.enpc.fr/~vandamme][M. Vandamme]]). This work was financially supported by Défi NEEDS MiPor.
  - Fatma ALLOUCHE (jan. 2013 - dec. 2013) :: /Methodologies and tools for the analysis of X-rays and electron tomography images/; Application to nanostructured materials and geomaterials (co-supervised with: [[http://navier.enpc.fr/BORNERT-Michel][M. Bornert]], N. Lenoir, [[http://www.icmpe.cnrs.fr/spip.php?article26][E. Leroy]], [[http://mateis.insa-lyon.fr/florent-dalmas][F. Dalmas]]). This work has benefited from a French government grant managed by ANR within the frame of the national program Investments for the Future ANR-11-LABX-022-01.

* Supervision of PhD Students

  - Othmane ZERHOUNI (oct. 2016 - ???) :: /Solids with a microstructure: imaging, virtual multi-scale microstructures and 3D printing/ (advisor: [[http://www.kostasdanas.com/][K. Danas]]).
  - Vinh Hoang Tan LE (oct. 2016 - ???) :: /Micromechanical modeling of cracking induced by hydromechanical stresses in heterogeneous porous materials by means of joint finite elements and inhomogeneity models with partial bonding of the interface/ (advisor: [[http://navier.enpc.fr/POUYA-Ahmad][A. Pouya]]).
  - Mohamed Hassan KHALILI (oct. 2013 - nov. 2016) :: /Micromechanics of creep in granular materials/ (advisor: [[http://navier.enpc.fr/ROUX-Jean-Noel][J.-N. Roux]]; co-supervisors [[http://navier.enpc.fr/BORNERT-Michel][M. Bornert]], [[http://navier.enpc.fr/PEREIRA-Jean-Michel][J.-M. Pereira]] and [[http://navier.enpc.fr/~vandamme][M. Vandamme]]).
  - Vinh-Phuc TRAN (oct. 2013 - oct. 2016) :: /Multiscale a priori probabilistic modelling of random heterogeneous materials/ (advisor: [[http://navier.enpc.fr/SAB-Karam][K. Sab]]; co-supervisor: [[http://msme.u-pem.fr/equipe-mecanique/personnel/enseignants-chercheurs/guilleminot-johann/][J. Guilleminot]]).
  - Yassine EL-ASSAMI (febr. 2012 - may 2015) :: Modelling time-dependent behaviour of concrete with the equivalent inclusion method (advisor: [[http://navier.enpc.fr/DORMIEUX-Luc][L. Dormieux]]).

* Publications in peer-reviewed journals

(see also [[https://cv.archives-ouvertes.fr/sbrisard][HAL]], [[http://scholar.google.fr/citations?user=IwlAZnAAAAAJ&hl=en][Google Scholar]], [[http://orcid.org/0000-0002-1976-6263][ORCID]])

** [[http://dx.doi.org/10.1007/s11340-017-0263-5][Khalili et al. (2017)]]
:PROPERTIES:
:CUSTOM_ID: KHAL2017
:HTML_CONTAINER_CLASS: sb-bibitem
:END:

M.H. Khalili, S. Brisard, M. Bornert, P. Aimedieu, J.-M. Pereira and J.-N. Roux, /Discrete Digital Projections Correlation: a reconstruction-free method to quantify local kinematics in granular media by X-ray tomography/, Experimental Mechanics, 2017 ([[https://hal-enpc.archives-ouvertes.fr/hal-01474701][preprint]])

** [[http://doi.org/10.1051/meca/2016037][Brisard (2017a)]]
:PROPERTIES:
:CUSTOM_ID: BRIS2017A
:HTML_CONTAINER_CLASS: sb-bibitem
:END:

S. Brisard, /Towards improved Hashin--Shtrikman bounds on the effective moduli of random composites/, Mechanics & Industry 18(2): 214, 2017 ([[https://hal-enpc.archives-ouvertes.fr/hal-01474668][post-print]])

** [[http://dx.doi.org/10.1002/nme.5263][Brisard (2017)]]
:PROPERTIES:
:CUSTOM_ID: BRIS2017
:HTML_CONTAINER_CLASS: sb-bibitem
:END:

S. Brisard, /Reconstructing displacements from the solution to the periodic Lippmann–Schwinger equation discretized on a uniform grid/, International Journal for Numerical Methods in Engineering 109(4): 459-486, 2017 ([[https://hal-enpc.archives-ouvertes.fr/hal-01304603][author's version]])

** [[https://doi.org/10.1520/ACEM20150030][Mayercsik et al. (2016)]]
:PROPERTIES:
:CUSTOM_ID: MAYE2016
:HTML_CONTAINER_CLASS: sb-bibitem
:END:

N. P. Mayercsik, S. Brisard, M. Vandamme and K. E. Kurtis, /Using Fractal Geometry to Recover the 3D Air Void, Scale-Independent, Microstructure Information From 2D Sections of Mortars/, Advances in Civil Engineering Materials 5(2): 1-21, 2016.

** [[http://dx.doi.org/10.1016/j.mechmat.2015.10.007][Tran et al. (2016)]]
   :PROPERTIES:
   :CUSTOM_ID: TRAN2016
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

V.P. Tran, J. Guilleminot, S. Brisard and K. Sab, /Stochastic modeling of mesoscopic elasticity random field/, Mechanics of Materials 93: 1-12, 2016 ([[https://hal-enpc.archives-ouvertes.fr/hal-01226337][author's version]])

** [[http://dx.doi.org/10.1016/j.ijsolstr.2013.10.037][Brisard et al (2014)]]
:PROPERTIES:
:CUSTOM_ID: BRIS2014
:HTML_CONTAINER_CLASS: sb-bibitem
:END:

S. Brisard, L. Dormieux and K. Sab, /A variational form of the
equivalent inclusion method for numerical homogenization/,
International Journal of Solids and Structures 51(3-4): 716-728, 2014
([[http://hal-enpc.archives-ouvertes.fr/hal-00922779][author's version]])

** [[https://doi.org/10.1016/j.cma.2014.05.014][Bignonnet et al. (2014)]]
:PROPERTIES:
:CUSTOM_ID: BIGN2014
:HTML_CONTAINER_CLASS: sb-bibitem
:END:

F. Bignonnet, K. Sab, L. Dormieux, S. Brisard and A. Bisson,
/Macroscopically consistent non-local modeling of heterogeneous
media/, Computer Methods in Applied Mechanics and Engineering 278(15):
218-238, 2014 ([[https://hal-enpc.archives-ouvertes.fr/hal-01076820][preprint]])

** [[http://dx.doi.org/10.1016/j.jmps.2013.08.009][Brisard et al (2013)]]
   :PROPERTIES:
   :CUSTOM_ID: BRIS2013A
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard, K. Sab and L. Dormieux, /New boundary conditions for the computation of the apparent stiffness of statistical volume elements/, Journal of the Mechanics and Physics of Solids 61(12): 2638-2658, 2013 ([[http://hal-enpc.archives-ouvertes.fr/hal-00871767][author's version]])

** [[http://link.aps.org/doi/10.1103/PhysRevE.87.013305][Brisard and Levitz (2013)]]
   :PROPERTIES:
   :CUSTOM_ID: BRIS2013
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard and P. Levitz, /Small-angle scattering of dense, polydisperse granular porous media: Computation free of size effects/, Physical Review E 87(1): 013305, 2013 ([[http://hal-enpc.archives-ouvertes.fr/hal-00779317][author's version]])

** [[http://dx.doi.org/10.1016/j.cma.2012.01.003][Brisard and Dormieux (2012)]]
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard and L. Dormieux, /Combining Galerkin approximation techniques with the principle of Hashin and Shtrikman to derive a new FFT-based numerical method for the homogenization of composites/, Computer Methods in Applied Mechanics and Engineering 217-220: 197-212, 2012 ([[http://hal-enpc.archives-ouvertes.fr/hal-00722361][author's version]])

** [[http://www.minsocam.org/msa/ammin/TOC/2012/FM12.html][Brisard et al (2012)]]
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard, R. S. Chae, I. Bihannic, L. Michot, P. Guttmann, J. Thieme, G. Schneider, P. J. M. Monteiro and P. Levitz, /Morphological quantification of hierarchical geomaterials by X-ray nano-CT bridges the gap from nano to micro length scales/, American Mineralogist 97(203): 480-483, 2012

** [[http://dx.doi.org/10.1016/j.commatsci.2010.08.032][Brisard et al (2010a)]]
   :PROPERTIES:
   :CUSTOM_ID: BRIS2010B
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard, L. Dormieux and D. Kondo, /Hashin-Shtrikman bounds on the shear modulus of a nanocomposite with spherical inclusions and interface effects/, Computational Materials Science 50(2): 403-410, 2010 ([[http://hal.archives-ouvertes.fr/hal-00539812][author's version]])

** [[http://dx.doi.org/10.1016/j.commatsci.2010.06.009][Brisard and Dormieux (2010)]]
   :PROPERTIES:
   :CUSTOM_ID: BRIS2010A
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard and L. Dormieux, /FFT-based methods for the mechanics of composites: a general variational framework/, Computational Materials Science 49(3): 663-671, 2010 ([[http://hal-enpc.archives-ouvertes.fr/hal-00722339][author's version]])

** [[http://dx.doi.org/10.1016/j.commatsci.2010.02.027][Brisard et al (2010)]]
   :PROPERTIES:
   :CUSTOM_ID: BRIS2010
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard, L. Dormieux and D. Kondo, /Hashin-Shtrikman bounds on the bulk modulus of a nanocomposite with spherical inclusions and interface effects/, Computational Materials Science 48(3): 589-596, 2010 ([[http://hal-enpc.archives-ouvertes.fr/hal-00904517][author's version]])

** [[http://dx.doi.org/10.2140/jomms.2009.4.263][Coussy and Brisard (2009)]]
   :PROPERTIES:
   :CUSTOM_ID: COUS2009
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

O. P. Coussy and S. Brisard, /Prediction of drying shrinkage beyond the pore isodeformation assumption/, Journal of Mechanics of Materials and Structures 4(2): 263-279, 2009

* Conferences

** Brisard and Chamoin (2016)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard, L. Chamoin, /Constitutive relation error for FFT-based methods/, VII European Congress on Computational Methods in Applied Sciences and Engineering (ECCOMAS Congress 2016), June 2016, Crete Island, Greece

** Tran et al. (2015b)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

V.P. Tran, S. Brisard, J. Guilleminot, K. Sab, /Stress-gradient materials: an analytical exploration/, Workshop on Computational Mechanics of Generalized Continua and Applications to Materials with Microstructure , Oct 2015, Catania, Italy ([[https://hal-enpc.archives-ouvertes.fr/hal-01226290][slides]])

** Khalili et al. (2015a)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

 M.H. Khalili, J.-N. Roux, J.-M. Pereira, M. Vandamme, S. Brisard, M. Bornert, /Internal states, stress-strain behavior and elasticity in oedometrically compressed model granular materials/, IV International Conference on Particle-based Methods -- Fundamentals and Applications, Sep 2015, Barcelona, Spain ([[https://hal-enpc.archives-ouvertes.fr/hal-01214733][paper]])

** Brisard and Chamoin (2015)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard, L. Chamoin, /A posteriori error estimators for FFT-based numerical techniques/, MAI workshop and training session: Micromechanics of cementitious materials, Sep 2015, Ecuelles, France ([[https://hal-enpc.archives-ouvertes.fr/hal-01199166][slides]])

** Brisard (2015a)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard, /Towards improved Hashin–Shtrikman bounds on the effective moduli of random composites/, 22ème Congrès Français de Mécanique, Aug 2015, Lyon, France ([[https://hal-enpc.archives-ouvertes.fr/hal-01187197][paper]], [[https://hal-enpc.archives-ouvertes.fr/hal-01187829][slides]])

** Tran et al. (2015a)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

V. P. Tran, J. Guilleminot, S. Brisard, K. Sab, /Homogénéisation numérique à l'aide de modèles prior de la raideur mésoscopique : identification et validation/, 22ème Congrès Français de Mécanique, Aug 2015, Lyon, France ([[https://hal-enpc.archives-ouvertes.fr/hal-01194370][paper]])

** Tran et al. (2015)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

V. P. Tran, J. Guilleminot, S. Brisard, K. Sab, /Stochastic Analysis of Mesoscopic Elasticity Random Rields obtained by Filtering Framework/, 13th US National Congress on Computational Mechanics (USNCCM13), Jul 2015, San Diego, United States ([[https://hal-enpc.archives-ouvertes.fr/hal-01194367][abstract]])

** Khalili et al. (2015)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

M.H. Khalili, S. Brisard, M. Bornert, J.-M. Pereira, M. Vandamme, J.-N. Roux, /A new method for measuring grain displacements in granular materials by X-ray computed tomography/, 2nd International Conference on Tomography of Materials and Structures (ICTMS 2015), Jun 2015, Quebec city, Canada ([[https://hal-enpc.archives-ouvertes.fr/hal-01194699][paper]])

** Brisard (2015)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard, /Overview of FFT-based homogenization techniques from the Galerkin point of view/, Conférence Internationale de Géotechnique, des Ouvrages et Structures (CIGOS 2015), May 2015, Cachan, France ([[https://hal-enpc.archives-ouvertes.fr/hal-01194693][paper]], [[https://hal-enpc.archives-ouvertes.fr/hal-01194695][slides]])

** Brisard et al. (2015)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard, M. Vandamme, B. Carrier, L. Wang, /Hydromechanical couplings in the clay matrix of argilite: some methodological aspects of the atomistic-to-continuum upscaling/, Multi-scale computational methods for bridging scales in materials and structures (EuroMech Colloquium 559), Feb 2015, Eindhoven, Netherlands ([[https://hal-enpc.archives-ouvertes.fr/hal-01194708][abstract]], [[https://hal-enpc.archives-ouvertes.fr/hal-01194710][poster]])

** Khalili et al. (2014)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

M.H. Khalili, S. Brisard, M. Bornert, J.-M. Pereira, M. Vandamme, J.-N. Roux, /New method for measuring grains displacement in granular materials by X-ray computed tomography/, Modeling Granular Media Across Scales, Jul 2014, Montpellier, France ([[https://hal-enpc.archives-ouvertes.fr/hal-01137696][abstract]])

** Brisard (2012)
   :PROPERTIES:
   :HTML_CONTAINER_CLASS: sb-bibitem
   :END:

S. Brisard and L. Dormieux, /A Galerkin approach to FFT-based homogenization methods/, ECCOMAS 2012, Sep 2012, Vienna, Austria ([[https://hal-enpc.archives-ouvertes.fr/hal-00738040][paper]])
