---
title: "Decomposition of transverse isotropic, fourth-rank tensors"
date: "2014-02-26"
---

In [a previous post](../20140112-Elastic_constants_of_an_isotropic_material-03),
I introduced the fourth-rank spherical and deviatoric projection tensors. Any
isotropic fourth-rank tensor is a linear combination of these two tensors; in
other words, the space of isotropic fourth-rank tensors (with minor and major
symmetries) is of dimension 2. Similarly, it can be shown ([Walpole,
1984](https://doi.org/10.1098/rspa.1984.0008)) that the space of
three-dimensional, *transverse isotropic* fourth-rank tensors (with minor and
major symmetries) is of dimension 6.  Furthermore; it is possible to produce a
convenient basis of this space.  This is the topic of the present post, which is
mostly based on the paper by Walpole
([1984](https://doi.org/10.1098/rspa.1984.0008)).


# Two second-rank projection tensors

It is recalled that transverse isotropy is defined by one single preferred
direction. In the present post, $\vec n$ denotes the unit vector which indicates
this preferred direction. Then, $\mathbf p$ and $\mathbf q$ are the following
projectors
$$
\mathbf p=\vec n\otimes\vec n,\quad\mathbf q=\boldsymbol{\delta}-\mathbf p.
$$ {#eq-01}

$\mathbf p$ is the projector onto the direction of anisotropy $\vec n$, while
$\mathbf q$ is the projection onto the plane of isotropy (orthogonal to
$\vec n$). It can readily be verified that
$$
\mathbf p\cdot\mathbf p=\mathbf p,\quad
\mathbf q\cdot\mathbf q=\mathbf q,\quad
\mathbf p\cdot\mathbf q=\mathbf q\cdot\mathbf p=\mathbf 0
$$
and
$$
\mathbf p:\mathbf p=1,\quad
\mathbf q:\mathbf q=2,\quad
\mathbf p:\mathbf q=\mathbf q:\mathbf p=0.
$$


# Tensor product of linear transformations

It will be convenient to introduce a new, Kronecker-like product of two
second-rank tensors, which Del Piero
([1979](https://doi.org/10.1007/BF00041097)) named *tensor product of linear
transformations*, and which will be denoted $\boxtimes{}$.

As a preliminary note, it should be observed that any fourth-rank tensor $\mathbf
A$ can be viewed as a endomorphism over the space of second-rank tensors, since
$\mathbf x\mapsto\mathbf A:\mathbf x$ is a linear mapping (the convention
adopted in this blog for the double dot product has been specified in a
[previous post]({filename}20140219-On_the_double_dot_product.md)). Therefore,
the fourth-rank tensor $\mathbf a\boxtimes\mathbf b$ ($\mathbf a, \mathbf b$:
second-rank tensors) can be defined by how it operates on second-rank tensors
$\mathbf x$
$$
\bigl(\mathbf a\boxtimes\mathbf b\bigr):\mathbf x=\mathbf a\cdot\mathbf x\cdot\mathbf b^{\mathsf{T}}.
$$ {#eq-02}

Writing the above definition in terms of the components of $\mathbf a$, $\mathbf b$
and $\mathbf x$, it is found that $\bigl(\mathbf a\boxtimes\mathbf b\bigr):\mathbf
x=a_{ik}\,x_{kl}\,b_{jl}\,\vec e_i\otimes\vec e_j$, which shows that the
components of $\mathbf a\boxtimes\mathbf b$ are
$$
\bigl(\mathbf a\boxtimes\mathbf b\bigr)_{ijkl}=a_{ik}\,b_{jl},
$$ {#eq-03}
from which it results
$$
\bigl(\mathbf a\boxtimes\mathbf b\bigr)^{\mathsf{T}}=\mathbf a^{\mathsf{T}}\boxtimes\mathbf b^{\mathsf{T}}.
$$

Given four second-rank tensors $\mathbf a$, $\mathbf b$, $\mathbf c$ and $\mathbf d$,
the following identity holds
$$
\bigl(\mathbf a\boxtimes\mathbf b\bigr):\bigl(\mathbf c\boxtimes\mathbf d\bigr)
=\bigl(\mathbf a\cdot\mathbf c\bigr)\boxtimes\bigl(\mathbf b\cdot\mathbf d\bigr).
$$ {#eq-04}

Indeed, let $\mathbf x$ be a second-rank tensor. Then, from Eq. (@eq-02)
$$
\begin{aligned}
\bigl(\mathbf a\boxtimes\mathbf b\bigr):\bigl(\mathbf c\boxtimes\mathbf d\bigr):\mathbf x
&=\bigl(\mathbf a\boxtimes\mathbf b\bigr):\bigl(\mathbf c\cdot\mathbf x\cdot\mathbf d^{\mathsf{T}}\bigr)=\mathbf a\cdot\bigl(\mathbf c\cdot\mathbf x\cdot\mathbf d^{\mathsf{T}}\bigr)\cdot\mathbf b^{\mathsf{T}}\\
&=\bigl(\mathbf a\cdot\mathbf c\bigr)\cdot\mathbf x\cdot\bigl(\mathbf d^{\mathsf{T}}\cdot\mathbf b^{\mathsf{T}}\bigr)=\bigl(\mathbf a\cdot\mathbf c\bigr)\cdot\mathbf x\cdot\bigl(\mathbf b\cdot\mathbf d\bigr)^{\mathsf{T}}\\
&=\bigl[\bigl(\mathbf a\cdot\mathbf c\bigr)\boxtimes\bigl(\mathbf b\cdot\mathbf d\bigr)\bigr]:\mathbf x.
\end{aligned}
$$

Eq. (@eq-03) shows that even if $\mathbf a$ and $\mathbf b$ are symmetric, the
tensor product $\mathbf a\boxtimes\mathbf b$ does not necessarily have the minor
symmetries. It will therefore be convenient to define $\mathbf a\overset{\mathrm
s}{\boxtimes}\mathbf b$, as the tensor $\mathbf a\boxtimes\mathbf b$,
*symmetrized with respect to the last two indices*
$$
\bigl(\mathbf a\overset{\mathrm s}{\boxtimes}\mathbf b\bigr)_{ijkl}=\frac12\bigl(a_{ik}\,b_{jl}+a_{il}\,b_{jk}\bigr),
$$
or, in intrinsic form ($\mathbf x$: second-rank tensor)
$$
\bigl(\mathbf a\overset{\mathrm s}{\boxtimes}\mathbf b\bigr):\mathbf x
=\frac12\bigl(\mathbf a\boxtimes\mathbf b\bigr):\bigl(\mathbf x+\mathbf x^{\mathsf T}\bigr)
=\frac12\mathbf a\cdot\bigl(\mathbf x+\mathbf x^{\mathsf T}\bigr)\cdot\mathbf b^{\mathsf T}.
$$ {#eq-05}

An identity similar to Eq. (@eq-04) can then be derived with $\overset{\mathrm
s}{\boxtimes}$
$$
\bigl(\mathbf a\overset{\mathrm s}{\boxtimes}\mathbf b\bigr):\bigl(\mathbf c\overset{\mathrm s}{\boxtimes}\mathbf d\bigr)
=\frac12\bigl[
\bigl(\mathbf a\cdot\mathbf c\bigr)\overset{\mathrm s}{\boxtimes}\bigl(\mathbf b\cdot\mathbf d\bigr)
+\bigl(\mathbf a\cdot\mathbf d\bigr)\overset{\mathrm s}{\boxtimes}\bigl(\mathbf b\cdot\mathbf c\bigr)
\bigr].
$$ {#eq-06}

The following identities, involving the second-rank projectors $\mathbf p$ and
$\mathbf q$ \[see Eq. (@eq-01)\], readily follow from Eq. (@eq-03)
$$
\begin{align}
\bigl(\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf p\bigr):\mathbf p&=\mathbf p,&\bigl(\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf p\bigr):\mathbf q&=\mathbf 0,\\
\bigl(\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf q\bigr):\mathbf p&=\mathbf 0,&\bigl(\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf q\bigr):\mathbf q&=\mathbf q,
\end{align}
$$
and
$$\bigl(\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf q\bigr):\mathbf p=\bigl(\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf q\bigr):\mathbf q=\bigl(\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf p\bigr):\mathbf p=\bigl(\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf p\bigr):\mathbf q=\mathbf 0.$$

Besides, the following multiplication table results from Eq. (@eq-06)

$:$ | $\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf p$ | $\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf q$ | $\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf p$ | $\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf q$
:-------------------------------------------------:|:--------------------------------------------------:|:---------:|:---------:|:-------------------------------------------------:
$\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf p$ | $\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf p$ | $\mathbf 0$ | $\mathbf 0$ | $\mathbf 0$
$\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf q$ | $\mathbf 0$                                          | $\mathbf 0$ | $\mathbf 0$ | $\mathbf 0$
$\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf p$ | $\mathbf 0$                                          | $\mathbf 0$ | $\mathbf 0$ | $\mathbf 0$
$\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf q$ | $\mathbf 0$                                          | $\mathbf 0$ | $\mathbf 0$ | $\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf q$

To conclude, it is observed that the fourth-rank tensor
$\mathbf{I}=\boldsymbol{\delta}\overset{\mathrm
s}{\boxtimes}\boldsymbol{\delta}$ maps any second-rank tensor to its symmetric
part: it reduces to the identity tensor over the space of second-rank, symmetric
tensors.


# Walpole\'s basis for transverse isotropic tensors

Walpole ([1984](https://doi.org/10.1098/rspa.1984.0008)) shows that any
transverse isotropic tensor is a linear combination of the six fourth-rank
tensors $\mathbf E_1$, $\mathbf E_2$, $\mathbf E_3$, $\mathbf E_4$, $\mathbf F$ and
$\mathbf G$ defined as follows
$$\mathbf E_1=\mathbf p\otimes\mathbf p,\quad\mathbf E_2=\frac12\mathbf q\otimes\mathbf q,\quad\mathbf E_3=\frac1{\sqrt2}\mathbf p\otimes\mathbf q,\quad\mathbf E_4=\frac1{\sqrt2}\mathbf q\otimes\mathbf p$$
$$\mathbf F=\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf q-\frac12\mathbf q\otimes\mathbf q,\quad\mathbf G=\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf q+\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf p.$$

Multiplication (in the sense of the double product) of these tensors is fairly
easy, as shown by the table below.

$:$    | $\mathbf E_1$ | $\mathbf E_2$ | $\mathbf E_3$ | $\mathbf E_4$ | $\mathbf F$ | $\mathbf G$
:-----------:|:------------:|:------------:|:------------:|:------------:|:---------:|:--------:
$\mathbf E_1$ | $\mathbf E_1$ | $\mathbf 0$    | $\mathbf E_3$ | $\mathbf 0$    | $\mathbf 0$ | $\mathbf 0$
$\mathbf E_2$ | $\mathbf 0$    | $\mathbf E_2$ | $\mathbf 0$    | $\mathbf E_4$ | $\mathbf 0$ | $\mathbf 0$
$\mathbf E_3$ | $\mathbf 0$    | $\mathbf E_3$ | $\mathbf 0$    | $\mathbf E_1$ | $\mathbf 0$ | $\mathbf 0$
$\mathbf E_4$ | $\mathbf E_4$ | $\mathbf 0$    | $\mathbf E_2$ | $\mathbf 0$    | $\mathbf 0$ | $\mathbf 0$
$\mathbf F$    | $\mathbf 0$    | $\mathbf 0$    | $\mathbf 0$    | $\mathbf 0$    | $\mathbf F$ | $\mathbf 0$
$\mathbf G$    | $\mathbf 0$    | $\mathbf 0$    | $\mathbf 0$    | $\mathbf 0$    | $\mathbf 0$ | $\mathbf G$

The above table must be read as: “row double dot column equals cell”. For
example, $\mathbf E_1:\mathbf E_3=\mathbf E_3$ and $\mathbf E_3:\mathbf E_1=\mathbf 0$.

## A convenient representation of transverse isotropic, fourth-rank tensors

Walpole ([1984](https://doi.org/10.1098/rspa.1984.0008)) proposes a convenient
representation of any transverse isotropic tensor $\mathbf T$, as the triplet $(A,
f, g)$ where $A$ is a 2×2 matrix and $f$ and $g$ are two scalars. This
representation should be understood as
$$
\mathbf T=a_{11}\,\mathbf E_1+a_{22}\,\mathbf E_2+a_{12}\,\mathbf E_3+a_{21}\,\mathbf E_4+f\,\mathbf F+g\,\mathbf G,
$$
where $a_{ij}$ are the coefficients of $A$. The condensed notation $\mathbf T=(A,
f, g)$ shall be adopted. Using the above multiplication table, it can readily be
verified that if $\mathbf T=(A, f, g)$ and $\mathbf T'=(A', f', g')$, then
$$
\mathbf T:\mathbf T'=(A\cdot A', ff', gg').
$$
This representation is particularly convenient when it comes to inverting
transverse isotropic tensors. Indeed,
$$\mathbf T^{-1}=(A^{-1}, 1/f, 1/g).
$$
Transposition is also straightforward
$$
\mathbf T^{\mathsf T}=(A^{\mathsf T}, f, g).
$$


# Decomposition of fourth-rank, isotropic tensors in Walpole's basis

The isotropic tensors $\mathbf{I}$, $\mathbf{J}$ and $\mathbf{K}$ introduced
[previously](../20140112-Elastic_constants_of_an_isotropic_material-03) can be
considered as transverse isotropic tensors. As such, they can be decomposed in
Walpole's basis. First, the identity tensor $\mathbf{I}$ decomposes as follows
$$
\begin{aligned}
\mathbf{I}&=\boldsymbol{\delta}\overset{\mathrm s}{\boxtimes}\boldsymbol{\delta}\\
&=\bigl(\mathbf p+\mathbf q\bigr)\overset{\mathrm s}{\boxtimes}\bigl(\mathbf p+\mathbf q\bigr)\\
&=\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf p+\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf q+\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf p+\mathbf q\overset{\mathrm s}{\boxtimes}\mathbf q\\
&=\mathbf E_1+\mathbf G+\mathbf F+\mathbf E_2.
\end{aligned}
$$
where the identity $\mathbf p\overset{\mathrm s}{\boxtimes}\mathbf p=\mathbf
p\otimes\mathbf p=\mathbf E_1$ has been used. Now, the decomposition of $\mathbf{J}$
is readily derived from its definition
$$
\begin{aligned}
3\mathbf{J}&=\boldsymbol{\delta}\otimes\boldsymbol{\delta}=\bigl(\mathbf p+\mathbf q\bigr)\otimes\bigl(\mathbf p+\mathbf q\bigr)\\
&=\mathbf p\otimes\mathbf p+\mathbf p\otimes\mathbf q+\mathbf q\otimes\mathbf p+\mathbf q\otimes\mathbf q\\
&=\mathbf E_1+\sqrt2\mathbf E_3+\sqrt2\mathbf E_4+2\mathbf E_2.
\end{aligned}
$$

Finally, the decomposition of the deviatoric projection tensor $\mathbf{K}$ is
found from the definition $\mathbf{K}=\mathbf{I}-\mathbf{J}$. To sum up
$$
\begin{gather}
\mathbf{I}=\bigl(\bigl[\begin{smallmatrix}1&0\\ 0&1\end{smallmatrix}\bigr], 1, 1\bigr),\\
\mathbf{J}=\bigl(\tfrac13\bigl[\begin{smallmatrix}1&\sqrt2\\\sqrt2&2\end{smallmatrix}\bigr], 0, 0\bigr),\\
\mathbf{K}=\bigl(\tfrac13\bigl[\begin{smallmatrix}2&-\sqrt2\\-\sqrt2&1\end{smallmatrix}\bigr], 1, 1\bigr).
\end{gather}
$$


# Conclusion

In the present post, a convenient decomposition of three-dimensional,
fourth-rank, transverse isotropic tensors as a linear combination of six basis
tensors has been proposed. Multiplication (in the sense of the [double dot
product](../20140219-On_the_double_dot_product)) of these basis tensors is
straightforward. Besides, representing transverse isotropic tensors as a
(matrix, scalar, scalar) triplet eases their multiplication and
inversion. Walpole's basis turns out to be very handy in many situations
(including the derivation of the Green operator for strains).

<!-- Local Variables: -->
<!-- mode: markdown -->
<!-- fill-column: 80 -->
<!-- End: -->
