# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: Towards polarization methods, part 2: the variational principle of Hashin and Shtrikman
#+DATE: <2011-10-19 Wed>
#+LINK: hash1962 https://doi.org/10.1016/0022-5096(62)90004-2

In [[file:./20111004-Towards_polarization_methods-01.org][part 1]] of this series, we introduced the Lippmann--Schwinger equation. Direct discretization of this equation can lead to efficient schemes for the numerical solution of the elementary problem of micromechanics. However, my experience shows that taking first the variational form of this equation, and following standard Garlerkin discretization approaches can lead to much more robust and efficient schemes. In this instalment, we will introduce the so-called variational "principle" of [[hash1962][Hashin and Shtrikman (1962)]], @@html:<!-- more -->@@ which is nothing but the variational form of the Lippmann-Schwinger equation. The present exposition follows quite closely the approach of [[https://doi.org/10.1016/0022-5096(77)90022-9][Willis (1977)]].

In the [[file:./20111004-Towards_polarization_methods-01.org][previous instalment]], I proved that solving the following elasticity problem on $\Omega$

\begin{align}
\label{eq:1}
\nabla_\vec x\cdot\stress&=\vec0&&(\vec x\in\Omega),\\
\label{eq:2}
\stress(\vec x)&=\stiffness(\vec x):\strain(\vec x)&&(\vec x\in\Omega),\\
\label{eq:3}
\strain(\vec x)&=\nabla_\vec x^\text s\vec{u}&&(\vec x\in\Omega),\\
\label{eq:4}
\vec{u}(\vec x)&=\Strain\cdot\vec x&&(\vec x\in\partial\Omega),
\end{align}

where $\Strain$ is the macroscopic strain, was equivalent to finding the polarization field $\tens{\tau}$ which solves the Lippmann-Schwinger equation

\begin{equation}
\label{eq:5}
\left(\stiffness-\stiffness_0\right)^{-1}:\tens{\tau}+\left(\tens{\Gamma}_0\circledast\tens{\tau}\right)=\Strain.
\end{equation}

In other words, the boundary value problem \eqref{eq:1} -- \eqref{eq:4} is replaced by a single integral equation \eqref{eq:5}. Classically, both sides of this equation are now multiplied by an arbitrary test field $\tens{\varpi}$. After integration over the domain $\Omega$ we find for all test fields $\tens{\varpi}$

\begin{equation}
\label{eq:6}
\volavg{\tens{\varpi}:\left(\stiffness-\stiffness_0\right)^{-1}:\tens{\tau}}+\volavg{\tens{\varpi}:\left(\tens{\Gamma}_0\circledast\tens{\tau}\right)}=\Strain:\volavg{\tens{\varpi}}.
\end{equation}

This is a standard variational problem. Indeed, introducing the bilinear form $a$ and the linear form $\ell$

\begin{align*}
a(\tens{\tau}, \tens{\varpi})&=\volavg{\tens{\varpi}:\left(\stiffness-\stiffness_0\right)^{-1}:\tens{\tau}}+\volavg{\tens{\varpi}:\left(\tens{\Gamma}_0\circledast\tens{\tau}\right)},\\
\ell(\tens{\varpi})&=\Strain:\volavg{\tens{\varpi}},
\end{align*}

Eq. \eqref{eq:6} can be written

\begin{equation}
\label{eq:7}
\text{Find }\tens{\tau}\,\text{such as }a(\tens{\tau}, \tens{\varpi})=\ell(\tens{\varpi})\,\text{for all }\tens{\varpi}.
\end{equation}

It should be noted that in order to be well-posed, the spaces to which $\tens{\tau}$ and $\tens{\varpi}$ belong should be specified. This can be done, and is actually the topic of a publication being currently reviewed.

Quite interestingly, it can easily be verified that Eq. \eqref{eq:7} in fact characterizes the critical point of the so-called functional of Hashin and Shtrikman, denoted here $\mathcal H$, and defined as

\begin{equation}
\label{eq:8}
\mathcal H(\tens{\tau})=\Strain:\volavg{\tens{\tau}}-\frac12\volavg{\tens{\tau}:\left(\stiffness-\stiffness_0\right)^{-1}:\tens{\tau}}-\frac12\volavg{\tens{\tau}:\left(\tens{\Gamma}_0\circledast\tens{\tau}\right)}.
\end{equation}

Indeed, for $\tens{\varpi}$ small enough, we have

\begin{equation}
\mathcal H(\tens{\tau}+\tens{\varpi})-\mathcal H(\tens{\tau})\simeq\ell(\tens{\varpi})-a(\tens{\tau}, \tens{\varpi}),
\end{equation}

the right-hand side being zero if the polarization field $\tens{\tau}$ is the solution to the Lippmann-Schwinger equation \eqref{eq:5}. Therefore, the first variation of $\mathcal H$ at $\tens{\tau}$ is null; in other words, $\tens{\tau}$ is a /critical point/ of $\mathcal H$. This result is usually referred to as the variational principle of [[hash1962][Hashin and Shtrikman (1962)]]. It is the fundamental result at the basis of all numerical methods presented in this blog.

So, it is time to sum up. We proved in this instalment that solving the boundary value problem \eqref{eq:1} -- \eqref{eq:4} is actually equivalent to finding the critical point of $\mathcal H$ defined by Eq. \eqref{eq:8}. It can be proved that this critical point is indeed unique. In the [[file:./20111031-Towards_polarization_methods-03.org][next instalment]] of this series, I will introduce the /energy principle/ of [[hash1962][Hashin and Shtrikman (1962)]]. In other words, we will explore under which circumstances this critical point is an /extremum/ of $\mathcal H$.
