# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: Towards polarization methods, part 3: the energy principle of Hashin and Shtrikman
#+DATE: <2011-10-31 Mon>
#+LINK: hash1962 https://doi.org/10.1016/0022-5096(62)90004-2
#+LINK: will1977 https://doi.org/10.1016/0022-5096(77)90022-9

In the [[file:./20111019-Towards_polarization_methods-02.org][second part]] of this series, I introduced the /variational/ principle of [[hash1962][Hashin and Shtrikman (1962)]]. It should be noted that this principle is valid, regardless of the reference material $\tens{C}_0$ (no restriction apply to the elastic moduli of the reference material). In the present instalment, we will see under which circumstances this principle is in fact an /energy/ principle.@@html:<!-- more -->@@ By energy principle, I mean that the functional of Hashin and Shtrikman $\mathcal H$ (see [[file:./20111019-Towards_polarization_methods-02.org][part 2]])

\begin{equation*}
\mathcal H(\tens{\tau})=\Strain:\volavg{\tens{\tau}}-\frac12\volavg{\tens{\tau}:\left(\tens{C}-\tens{C}_0\right)^{-1}:\tens{\tau}}-\frac12\volavg{\tens{\tau}:\left(\tens{\Gamma}_0\circledast\tens{\tau}\right)},
\end{equation*}

is /extremum/ at the solution of the Lippmann-Schwinger equation (we already know that it is /stationary/).

This instalment will in fact be very short, as you will be spared the proof of the main result. As in [[file:./20111019-Towards_polarization_methods-02.org][part 2]], all details can be found in [[hash1962][Hashin and Shtrikman (1962)]] [see also [[will1977][Willis (1977)]] for a slightly more modern proof]. So, here goes.

#+BEGIN_THEOREM
Let $\tens{\tau}$ be the unique solution of the Lippmann-Schwinger equation (see [[file:./20111004-Towards_polarization_methods-01.org][part 1]])

\begin{equation*}
\left(\tens{C}-\tens{C}_0\right)^{-1}:\tens{\tau}+\tens{\Gamma}_0\circledast\tens{\tau}=\Strain.
\end{equation*}

If the reference material is stiffer (resp. softer) than the heterogeneous material, then $\mathcal H$ is minimum (resp. maximum) at $\tens{\tau}$. More precisely
  - if $\tens{C}(\vec x)-\tens{C}_0$ is positive, semi-definite at every point $\vec x\in\Omega$, then
\begin{equation*}
\text{for all}\;\tens{\varpi}(\vec x),\mathcal H(\tens{\varpi})\leq\mathcal H(\tens{\tau}),
\end{equation*}
  - if $\tens{C}(\vec x)-\tens{C}_0$ is negative, semi-definite at every point $\vec x\in\Omega$, then
\begin{equation*}
\text{for all}\;\tens{\varpi}(\vec x),\mathcal H(\tens{\varpi})\geq\mathcal H(\tens{\tau}).
\end{equation*}
#+END_THEOREM

Maybe a quick reminder would be useful, here. $\tens{C} - \tens{C}_0$ is said to be positive, semi-definite, if $\tens{\varpi}:\tens{C}:\tens{\varpi}\geq\tens{\varpi}:\tens{C}_0:\tens{\varpi}$ for all $\tens{\varpi}$. For isotropic heterogeneous (resp. reference) materials with bulk modulus $\kappa$ (resp. $\kappa_0$) and shear modulus $\mu$ (resp. $\mu_0$), this is equivalent to

\begin{equation*}
\kappa\geq\kappa_0\quad\text{and}\quad\mu\geq\mu_0.
\end{equation*}

Note that it is not always possible to find a reference material which complies with the requirements of the above theorem. A typical example would be a heterogeneous material conaining both pores [$\tens{C}(\vec x) = \tens 0$] and rigid inclusions [$\tens{C}(\vec x)\rightarrow+\infty$]. We won't address this issue for the time being.

Extremum principles are very useful in practice, as they usually lead to well-behaved numerical schemes. The energy principle of Hashin and Shtrikman also has deep theoretical consequences, as will be seen in the [[file:./20111210-Towards_polarization_methods-04.org][next instalment]] of this series.
