# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: Towards polarization methods, part 1: the Lippmann--Schwinger equation
#+DATE: <2011-10-04 Tue>

In this series, we will enter the heart of the matter. We will look at non-standard ways of numerically solving the local problem of micromechanics, introducing first the Lippmann--Schwinger equation (in this instalment), then the energy principle of Hashin and Shtrikman (in the next instalment).@@html:<!-- more -->@@

We again consider a heterogeneous material, with local stiffness $\tens{C}$, located in domain $\Omega\subset\reals^d$. As will be discussed elsewhere, the local problem of micromechanics reads

\begin{align}
    \label{eq:1}
    \nabla_\vec x\cdot\stress&=\vec0&&(\vec x\in\Omega),\\
    \label{eq:2}
    \stress(\vec x)&=\tens{C}(\vec x):\tens{\varepsilon}(\vec x)&&(\vec x\in\Omega),\\
    \label{eq:3}
    \tens{\varepsilon}(\vec x)&=\nabla_\vec x^\text s\vec{u}&&(\vec x\in\Omega),\\
    \label{eq:4}
    \vec{u}(\vec x)&=\overline{\tens{\varepsilon}}\cdot\vec x&&(\vec x\in\partial\Omega),
\end{align}

where $\overline{\tens{\varepsilon}}$ is the macroscopic (imposed) strain. The solution to this problem defines the effective elastic properties $\tens{C}^\text{eff}$, since, by definition

\begin{equation*}
\overline{\tens{\sigma}}=\volavg{\stress}=\tens{C}^\text{eff}:\overline{\tens{\varepsilon}},
\end{equation*}

where $\overline{\tens{\sigma}}$ is the macroscopic stress.

Eqs. \eqref{eq:1} -- \eqref{eq:4} would be trivial if we had $\tens{C}(\vec x)=\tens{C}_0$ for any $\vec x\in\Omega$ ($\tens{C}_0$ is a /constant/ stiffness tensor). Indeed, the solution would then be

\begin{equation*}
\tens{\varepsilon}(\vec x)=\overline{\tens{\varepsilon}},\qquad\stress(\vec x)=\tens{C}_0:\overline{\tens{\varepsilon}}.
\end{equation*}

In other words, our life would be easier if we were to homogenize materials which are /already/ homogeneous!

So we see that the complexity of Eqs. \eqref{eq:1} -- \eqref{eq:4} comes from the heterogeneity of the material. We would like to /force/ a homogeneous material /into/ this problem. More precisely, we select a so-called /reference/ material, with /arbitrary/ stiffness $\tens{C}_0$. Then the local stress-strain relationship \eqref{eq:2} can always be written as follows

\begin{equation}
\label{eq:5}
\stress(\vec x)=\tens{C}(\vec x):\tens{\varepsilon}(\vec x)=\tens{C}_0:\tens{\varepsilon}(\vec x)+\left[\tens{C}(\vec x)-\tens{C}_0\right]:\tens{\varepsilon}(\vec x).
\end{equation}

Introducing the so-called /polarization/ $\tens{\tau}$

\begin{equation}
\label{eq:6}
\tens{\tau}(\vec x)=\left[\tens{C}(\vec x)-\tens{C}_0\right]:\tens{\varepsilon}(\vec x),
\end{equation}

Eq. \eqref{eq:5} then takes the following compact form

\begin{equation}
\label{eq:7}
\stress(\vec x)=\tens{C}_0:\tens{\varepsilon}(\vec x)+\tens{\tau}(\vec x).
\end{equation}

Determination of the polarization $\tens{\tau}$ requires the solution to Eqs. \eqref{eq:1} -- \eqref{eq:4}; therefore, it would seem that Eq. \eqref{eq:7} achieved nothing! However, let us assume for a moment that we /know/ $\tens{\tau}$ beforehand. Then Eqs. (1) -- (4) reduce to

\begin{align*}
\nabla_\vec x\cdot\stress&=\vec0&&(\vec x\in\Omega),\\
\stress(\vec x)&=\tens{C}_0:\tens{\varepsilon}(\vec x)+\tens{\tau}(\vec x)&&(\vec x\in\Omega),\\
\tens{\varepsilon}(\vec x)&=\nabla_\vec x^\text s\vec{u}&&(\vec x\in\Omega),\\
\vec{u}(\vec x)&=\overline{\tens{\varepsilon}}\cdot\vec x&&(\vec x\in\partial\Omega),
\end{align*}

which characterize the elastic equilibrium of a /homogeneous/, /prestressed/ linear elastic material $\tens{C}_0$. From [[file:./20110911-The_Green_operator_for_strains-01.org][this series]], the solution to the above problem is known (at least, formally)

\begin{equation}
\label{eq:8}
\tens{\varepsilon}(\vec x)=\overline{\tens{\varepsilon}}-(\tens{\Gamma}_0\circledast\tens{\tau})(\vec x),
\end{equation}

where the Green operator for strains $\tens{\Gamma}_0$ associated with $\tens{C}_0$ has been introduced. We now need to remember that the polarization $\tens{\tau}$ is /not/ known. Rather, it is given by Eq. \eqref{eq:6}. Upon introduction into Eq. \eqref{eq:8}, we get the so-called Lippmann--Schwinger equation

\begin{equation}
\label{eq:9}
\tens{\varepsilon}(\vec x)+\left\{\tens{\Gamma}_0\circledast\left[\left(\tens{C}-\tens{C}_0\right):\tens{\varepsilon}\right]\right\}(\vec x)=\overline{\tens{\varepsilon}}.
\end{equation}

This equation was first introduced by [[https://doi.org/10.1002/pssb.2220550241][Zeller and Dederichs (1973)]]. In the next instalments of this series, it will be more convenient to chose the polarization $\tens{\tau}$, rather that the strain $\tens{\varepsilon}$ as principal unknown. This leads to the equivalent integral equation

\begin{equation}
\label{eq:10}
\left[\tens{C}(\vec x)-\tens{C}_0\right]^{-1}:\tens{\tau}(\vec x)+\left(\tens{\Gamma}_0\circledast\tens{\tau}\right)(\vec x)=\overline{\tens{\varepsilon}}.
\end{equation}

To sum up, we started with the set of partial differential equations \eqref{eq:1} -- \eqref{eq:4}, and ended up with one /single/, /equivalent/, integral equation. Discretization of the Lippmann-Schwinger equation \eqref{eq:9} has already been considered in the past. This leads to some well-known numerical schemes ([[https://doi.org/10.1016/S0045-7825(97)00218-1][Moulinec & Suquet, 1998]]).

However, I do think it is not the best way to proceed. A much more fruitful approach is to consider the variational form of Eq. \eqref{eq:10}. This will be done in the [[file:./20111019-Towards_polarization_methods-02.org][next instalment]] of this series.
