# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: The Green operator for strains, part 2: elementary properties
#+DATE: <2011-09-18 Sun>

In [[file:./20110911-The_Green_operator_for_strains-01.org][part 1]] of this series, we have seen how the Green operator for strains ($\tens{\Gamma}_0$) was defined as the operator providing the solution to the problem of elastic equilibrium of a /prestressed/ homogeneous domain. In this instalment, some simple, but useful properties of this operator will be proved.@@html:<!-- more -->@@ We again consider the bounded domain $\Omega\subset\reals^d$, occupied by a homogeneous, linearly elastic material with stiffness $\tens{C}_0$. $\tens{\Gamma}_0$ denotes the Green operator for strains for the material $\tens{C}_0$, over the domain $\Omega$. The first property is a direct consequence of the definition of $\tens{\Gamma}_0$, given in [[file:./20110911-The_Green_operator_for_strains-01.org][part 1]].

* Application to self-equilibrated prestresses

We consider a /self-equilibrated/ prestress $\tens{\varpi}$ (that is, $\nabla\cdot\tens{\varpi}=\tens0$). We will prove that $\tens{\Gamma}_0\circledast\tens{\varpi}=\tens0$. By definition of the Green operator, $\tens{\Gamma}_0\circledast\tens{\varpi}=-\strain$, where $\strain$ is the strain which solves the following problem
\begin{align}
\label{eq:1}
\nabla_{\vec x}\cdot\left(\tens{C}_0:\strain+\tens{\varpi}\right)&=\vec{0}&&(\vec x\in\Omega),\\
\label{eq:2}
\strain(\vec x)&=\nabla_\vec x^\text{s}\vec{u}&&(\vec x\in\Omega),\\
\label{eq:3}
\vec{u}(\vec x)&=\vec 0&&(\vec x\in\partial\Omega).
\end{align}

Since $\nabla\cdot\tens{\varpi}=\vec 0$, it is found that Eq. \eqref{eq:1} reduces to
\begin{align*}
    \nabla_{\vec x}\cdot\left(\tens{C}_0:\strain\right)&=\vec{0}&&(\vec x\in\Omega).
\end{align*}

Obviously, the solution to Eqs. \eqref{eq:1}, \eqref{eq:2} and \eqref{eq:3} is $\vec{u}=\vec 0$ (and $\strain=\nabla^\text{s}\vec{u}=\tens0$). Since $\tens{\Gamma}_0\circledast\tens{\varpi}=-\strain$, it is finally found that $\tens{\Gamma}_0\circledast\tens{\varpi}=\tensiv 0$. To sum up, we have proved the following property

#+BEGIN_THEOREM
For any self-equilibrated prestress $\tens{\varpi}$
\begin{equation*}
    \tens{\Gamma}_0\circledast\tens{\varpi}=\tens 0.
\end{equation*}
#+END_THEOREM

* "Square" of the Green operator

Application of the previous result leads to a useful property, which can be found in e.g. [[https://doi.org/10.1007/978-3-7091-2780-3_5][Willis (2001)]], where it is written somewhat abusively (but quite efficiently!) $\tens{\Gamma}_0\tens{C}_0\tens{\Gamma}_0=\tens{\Gamma}_0$.

Let $\strain=-\tens{\Gamma}_0\circledast\tens{\varpi}$, and $\stress=\tens{C}_0:\strain+\tens{\varpi}$. By definition of $\tens{\Gamma}_0$, $\strain$ is geometrically compatible and $\stress$ is self-equilibrated: $\nabla\cdot\stress=\tens 0$. From the previous property, we have $\tens{\Gamma}_0\circledast\stress=\tens0$. In other words
\begin{equation*}
    \tens{\Gamma}_0\circledast\left(\tens{C}_0:\strain+\tens{\varpi}\right)=\tens0
\end{equation*}
and, since $\strain=-\tens{\Gamma}_0\circledast\tens{\varpi}$, we find the following property:

#+BEGIN_THEOREM
For any prestress $\tens{\varpi}$,
\begin{equation*}
    \tens{\Gamma}_0\circledast\left[\tens{C}_0:\left(\tens{\Gamma}_0\circledast\tens{\varpi}\right)\right]=\tens{\Gamma}_0\circledast\tens{\varpi}.
\end{equation*}
#+END_THEOREM

* Volume average

To close this instalment, we again consider a prestress $\tens{\varpi}$, and the associated strain $\strain=-\tens{\Gamma}_0\circledast\tens{\varpi}$. We seek the value of $\volavg\strain$, where overlined quantities denote /volume averages/
\begin{equation*}
    \volavg{\strain} = \frac 1{\meas{\Omega}}\int_\Omega\strain(\vec x)\dV{\vec x}.
\end{equation*}

Using Stokes' theorem, and the definition of $\vec{u}$
\begin{equation*}
    \volavg\strain=\frac1{\meas{\Omega}}\int_\Omega\nabla_\vec x^\text s\vec{u}\dV{\vec x}=\frac1{2\meas{\Omega}}\int_{\partial\Omega}\left[\vec{u}(\vec x)\otimes\vec n(\vec x)+\vec n(\vec x)\otimes\vec{u}(\vec x)\right]\dS{\vec x},
\end{equation*}
where $\vec{u}$ is the displacement associated to the strain $\strain$, and $\vec n$ is the outward normal to the boundary $\partial\Omega$ of the domain $\Omega$. From the boundary condition \eqref{eq:3}, we finally find $\volavg\strain=\tens0$. Finally

#+BEGIN_THEOREM
For any prestress $\tens{\varpi}$,
\begin{equation*}
    \volavg{\tens{\Gamma}_0\circledast\tens{\varpi}}=\tens 0.
\end{equation*}
#+END_THEOREM
