# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: Elastic constants of an isotropic material, part 2: plane strain elasticity
#+DATE: <2013-12-29 Sun>

In the [[file:./20131205-Elastic_constants_of_an_isotropic_material-01.org][previous instalment]] of this series, I introduced the constitutive law of an isotropically elastic material, and the related material constants, within the framework of 3D elasticity. I will now address the case of plane strain elasticity.@@html:<!-- more -->@@

Problems of plane strain elasticity are defined as problems where the following components of the strain tensor are null
\begin{equation}
    \label{eq:1}
    \varepsilon_{31} = \varepsilon_{23} = \varepsilon_{33} = 0.
\end{equation}

This is typically true of problems for which the geometry /and the loading/ are invariant along the third direction $\vec e_3$. In what follows, it will be covenient to adopt the following classical notation

  - latin indices (e.g. $i, j, k$) can take values in $\{1, 2, 3\}$,
  - greek indices (e.g. $\alpha, \beta, \gamma$) can take values in $\{1, 2\}$.

In both cases, Einstein's convention applies; in other words, $\varepsilon_{kk}$ stands for
\begin{equation*}
    \sum_{k=1}^3\varepsilon_{kk},
\end{equation*}
while $\varepsilon_{\gamma\gamma}$ stands for
\begin{equation*}
    \sum_{\gamma=1}^2\varepsilon_{\gamma\gamma}.
\end{equation*}

As in the previous instalment, the constitutive laws in isotropic, plane strain elasticity will be derived using various sets of material constants, starting with the bulk modulus $E$ and the Poisso ratio $\nu$.

* Young's modulus and Poisson ratio

We first recall the consitutive law in isotropic, 3D elasticity
\begin{equation}
    \label{eq:2}
    \varepsilon_{ij}=\frac{1+\nu}E\sigma_{ij}-\frac\nu E\sigma_{kk}\delta_{ij}.
\end{equation}

Combination of Eqs. \eqref{eq:1} and \eqref{eq:2} for $(i, j)=(3, 1)$ and $(i, j)=(2, 3)$, first leads to $\sigma_{31}=\sigma_{23}=0$. Then, for $(i, j) = (3, 3)$, $\sigma_{33}=\nu\sigma_{\gamma\gamma}$. The 3D trace of $\stress$ can therefore be expressed as a function of its 2D trace
\begin{equation*}
    \sigma_{kk}=\left(1+\nu\right)\sigma_{\gamma\gamma}.
\end{equation*}

Substituting in Eq. \eqref{eq:2}
\begin{equation}
    \label{eq:3}
    \varepsilon_{\alpha\beta}=\frac{1+\nu}E\left(\sigma_{\alpha\beta}-\nu\sigma_{\gamma\gamma}\delta_{\alpha\beta}\right),
\end{equation}
which is the plane strain constitutive low we were looking for.

* Shear modulus and Poisson ratio

Recalling (see [[file:./20131205-Elastic_constants_of_an_isotropic_material-01.org][previous instalment]]) that $E=2\shearmod\left(1+\nu\right)$, Eq. \eqref{eq:2} can also be cast as follows
\begin{equation}
    \label{eq:4}
    \varepsilon_{\alpha\beta}=\frac1{2\shearmod}\left(\sigma_{\alpha\beta}-\nu\sigma_{\gamma\gamma}\delta_{\alpha\beta}\right).
\end{equation}

* Bulk and shear moduli

For (2D) isotropic stresses, $\sigma_{\alpha\beta}=-p\delta_{\alpha\beta}$, Eq. \eqref{eq:4} reads
\begin{equation*}
    \varepsilon_{\alpha\beta}=-\frac{1-2\nu}{2\shearmod}p\delta_{\alpha\beta},
\end{equation*}
and the relative surface change $\varepsilon_\text s$, defined as $\varepsilon_\text s=\varepsilon_{\gamma\gamma}$, reads
\begin{equation*}
    \varepsilon_\text s=-\frac p{\kappa_\text{2D}},
\end{equation*}
with
\begin{equation}
    \label{eq:5}
    \kappa_\text{2D}=\frac\shearmod{1-2\nu}.
\end{equation}

$\kappa_\text{2D}$ thus defined is the 2D (plane strain) bulk modulus of the material. Attention should be paid to the fact that, unlike the shear modulus, the bulk modulus of a material /depends on the dimension of the physical space/. More generally, the (2D) trace of the strain tensor is related to the average stress
\begin{equation}
    \label{eq:6}
    \varepsilon_{\gamma\gamma}=\frac{1-2\nu}{2\shearmod}\sigma_{\gamma\gamma}.
\end{equation}

Combining Eqs. \eqref{eq:4} and \eqref{eq:6}
\begin{equation*}
    \sigma_{\alpha\beta}=2\shearmod\varepsilon_{\alpha\beta}+\frac{2\shearmod\nu}{1-2\nu}\varepsilon_{\gamma\gamma}\delta_{\alpha\beta}=\frac{\shearmod}{1-2\nu}\varepsilon_{\gamma\gamma}\delta_{\alpha\beta}+2\shearmod\left(\varepsilon_{\alpha\beta}-\frac{\varepsilon_{\gamma\gamma}}2\delta_{\alpha\beta}\right),
\end{equation*}
and the stress-strain relationship finally reads
\begin{equation*}
    \sigma_{\alpha\beta}=\kappa_\text{2D}\varepsilon_{\gamma\gamma}\delta_{\alpha\beta}+2\shearmod\left(\varepsilon_{\alpha\beta}-\frac{\varepsilon_{\gamma\gamma}}2\delta_{\alpha\beta}\right).
\end{equation*}

* Conclusion

In this instalment, we have seen how the plane strain asumption affects the constitutive law of isotropic, linear and elastic materials. In particular, the bulk modulus which is the ratio of the average stress to the relative surface change appears to be dimension dependent. In the [[file:./20140112-Elastic_constants_of_an_isotropic_material-03.org][next instalment]], we will reconcile the 3D and 2D points of view.
