# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: Elastic constants of an isotropic material, part 3: putting it all together
#+DATE: <2014-01-12 Sun>

In the previous instalments of this series (see [[file:./20131205-Elastic_constants_of_an_isotropic_material-01.org][Part 1]] and [[file:./20131229-Elastic_constants_of_an_isotropic_material-02.org][Part 2]], I have shown that regardless of the dimensionality (3D or plane strain elasticity), the constitutive law of an isotropically elastic material reads

\begin{equation}
\label{eq:1}
\sigma_{ij}=\kappa\varepsilon_{kk}\delta_{ij}+2\mu\left(\varepsilon_{ij}-\frac{\varepsilon_{kk}}d\delta_{ij}\right),
\end{equation}

where $d$ is the dimension of the physical space ($d=3$ for 3D elasticity, $d=2$ for plane strain elasticity), $\mu$ is the shear modulus, and $\kappa$ is the bulk modulus, whose expression depends on $d$

\begin{align}
\label{eq:2}\kappa&=\frac23\frac{1+\nu}{1-2\nu}\mu&&(d=3),\\
\label{eq:3}\kappa&=\frac\mu{1-2\nu}&&(d=2).
\end{align}

In this instalment, I am going to introduce some classical isotropic, fourth-rank tensors which will prove extremely useful and will allow us to cast Eq. \eqref{eq:1} in an intrinsic (component-free) form.@@html:<!-- more -->@@ It should be noted that the following developments are restricted to fourth-rank tensors $\tensiv T$ with both /minor/ and /major/ symmetries

\begin{align*}
T_{ijkl}&=T_{jikl}=T_{ijlk}&&\text{(minor symmetries)},\\
T_{ijkl}&=T_{klij}&&\text{(major symmetries)}.
\end{align*}

* Spherical and deviatoric projection tensors

In the present section, I am going to introduce the fourth-rank identity, spherical and deviatoric projection tensors.

** Fourth-rank identity tensor

The fourth-rank identity tensor $\tens{I}$ maps any second-rank, symmetric tensor $\tens u$ to itself

\begin{equation*}
\tens{I}:\tens u=\tens u.
\end{equation*}

It is straightforward to work out the components of $\tens{I}$ (accounting for both minor and major symmetries)

\begin{equation*}
I_{ijkl}=\frac12\left(\delta_{ik}\delta_{jl}+\delta_{il}\delta_{jk}\right).
\end{equation*}

** Fourth-rank spherical projection tensor

The fourth-rank spherical projection tensor $\tens{J}$ extracts the spherical part of any symmetric, second-rank tensor $\tens u$

\begin{equation*}
\tens{J}:\tens u=\frac1d\tr(\tens u)\tens{\delta},
\end{equation*}

where $\tens{\delta}$ is the second-rank identity tensor (with components $\delta_{ij}$). In particular, $\tens{J}:\tens{\delta}=\tens{\delta}$. In intrinsic form, $\tens{J}$ reads

\begin{equation*}
\tens{J}=\frac1d\tens{\delta}\otimes\tens{\delta},
\end{equation*}

where $\otimes$ denotes the [[http://en.wikipedia.org/wiki/Tensor_product][tensor product]]. The components of $\tens{J}$ are

\begin{equation*}
J_{ijkl} = \frac1d\delta_{ij}\delta_{kl}.
\end{equation*}

** Fourth-rank deviatoric projection tensor

The fourth-rank deviatoric projection tensor $\tens{K}$ extracts the deviatoric part of any symmetric, second-rank tensor $\tens u$

\begin{equation*}
\tens{K}:\tens u=\tens u-\frac1d\tr(\tens u)\tens{\delta}=\tens u-\tens{J}:\tens u,
\end{equation*}

from which it results that

\begin{equation*}
\tens{K}=\tens{I}-\tens{J}.
\end{equation*}

* Stiffness tensor

Going back the constitutive law of the linearly elastic, isotropic material given by Eq. \eqref{eq:1}, it is found that

\begin{equation*}
\stress=d\kappa\tens{J}:\strain+2\mu\tens{K}:\strain=\tens{C}:\strain,
\end{equation*}

where $\tens{C}$ is the fourth-rank stiffness tensor of the material

\begin{equation*}
\tens{C}=d\kappa\tens{J}+2\mu\tens{K}.
\end{equation*}

In isotropic elasticity, the stiffness tensor is a linear combination of the two tensors $\tens{J}$ and $\tens{K}$. This is in fact a general result, which is heavily used in materials science: any /isotropic/ fourth-rank tensor with minor and major symmetries is a linear combination of $\tens{J}$ and $\tens{K}$. In other words, $\left(\tens{J}, \tens{K}\right)$ forms a /basis/ of the fourth-rank isotropic tensors with minor and major symmetries. Why this is useful will become obvious in the next section, where I will show that algebra in this basis is dead simple.

* Algebra of the $\tens{J}$ and $\tens{K}$ tensors

It can readily be verified that

\begin{gather*}
\tens{J}:\tens{J}=\tens{J},\\
\tens{K}:\tens{K}=\tens{K},\\
\tens{K}:\tens{J}=\tens{J}:\tens{K}=\tens0.
\end{gather*}

Therefore, multiplication of two isotropic tensors $\tensiv T_i=a_i\tens{J}+b_i\tens{K}$ ($i=1,2$) is trivial

\begin{equation*}
\tensiv T_1:\tensiv T_2=a_1a_2\tens{J}+b_1b_2\tens{K}.
\end{equation*}

Also, inversion of an isotropic tensor $\tensiv T=a\tens{J}+b\tens{K}$ is straightforward

\begin{equation*}
\tensiv T^{-1}=\frac1a\tens{J}+\frac1b\tens{K}.
\end{equation*}

All these expressions will prove extremely useful in due time.

* Conclusion

This is the end of this series on the elastic constants of isotropic materials. I have shown that (regardless of the dimension $d$ of the physical space), such materials are characterized by two constants. The shear modulus $\mu$, the Poisson ratio $\nu$ and Young's modulus $E$ do not depend on $d$, while the plane strains expression of the bulk modulus $\kappa$ differs from its 3D expression (see Eqs. \eqref{eq:2} and \eqref{eq:3}).

This series was also a good opportunity to introduce the tensors $\tens{J}$ and $\tens{K}$, which form a basis for the isotropic, fourth-rank tensors. Using this basis is very convenient, as algebra within this basis is extremely simple.
