# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: The periodic Green operator for strains
#+DATE: <2014-03-06 Thu>

# Equation numbers
# 1, 2, 3, 4, 5, 6, 7, 8, 9, 10

#+BEGIN_ABSTRACT
The Green operator for strains is defined as the linear operator which maps --in a homogeneous material-- the local prestress to the (opposite of the) local strain. Closed-form expressions of this operator can be derived in the case of periodic boundary conditions, as will be demonstrated in the present post.
#+END_ABSTRACT

Let $\stiffness$ be the stiffness of a homogeneous, linearly elastic material occupying the whole, $d$-dimensional, space $\reals^d$. This material is submitted to the local, $(L_1,\cdots,L_d)$-periodic prestress $\prestress(\vec x)$. The elastic equilibrium of this medium is governed by the following equations over $\reals^d$

\begin{align}
\label{eq:1}
\nabla_\vec x\cdot\stress&=\vec0 & (\vec x\in\reals^d)\\
\label{eq:2}
\stress(\vec x)&=\stiffness:\strain(\vec x)+\prestress(\vec x)&(\vec x\in\reals^d)\\
\label{eq:3}
\strain(\vec x)&=\nabla_\vec x^\text s\vec{u}&(\vec x\in\reals^d)\\
\label{eq:4}
\vec{u}(\vec x+L_i\vec e_i)&=\vec{u}(\vec x)&(\vec x\in\reals^d)\\
\end{align}

It should be noted that in Eq. \eqref{eq:4}, no summation should be carried out on the repeated index $i$. For this problem to be well-posed, the functional space to which the displacement belongs should be specified; this is beyond the scope of this post. Eqs. \eqref{eq:1} to \eqref{eq:4} are conveniently solved in Fourier space. Indeed, since the local displacement $\vec{u}$ is periodic, it can be decomposed in a Fourier series

\begin{equation}
\label{eq:5}
\vec{u}(\vec x)=\sum_{b\in\integers^d}\hat\vec{u}_b\exp(i\vec k_b\cdot\vec x),
\end{equation}

with

\begin{equation}
\label{eq:10}
\vec k_b=\frac{2\pi b_1}{L_1}\vec e_1+\cdots+\frac{2\pi b_d}{L_d}\vec e_d,
\end{equation}

and

\begin{equation*}
\hat\vec{u}_b=\frac1{\meas{\Omega}}\int_\Omega\vec{u}(\vec x)\exp(-i\vec k_b\cdot\vec x)\dV{\vec x},
\end{equation*}

where $b=(b_1,\ldots,b_d)\in\integers^d$ is a multi-index, and $\Omega=(0,L_1)\times\cdots\times(0,L_d)$ denotes the unit-cell. Similarly, the strain $\strain$, stress $\stress$ and prestress $\prestress$ are expanded in Fourier series

\begin{align*}
\strain(\vec x)&=\sum_{b\in\integers^d}\hat\strain_b\exp(i\vec k_b\cdot\vec x),\\
\stress(\vec x)&=\sum_{b\in\integers^d}\hat\stress_b\exp(i\vec k_b\cdot\vec x),\\
\prestress(\vec x)&=\sum_{b\in\integers^d}\hat\prestress_b\exp(i\vec k_b\cdot\vec x).
\end{align*}

Eq. \eqref{eq:3} then reads

\begin{align*}
\hat\strain_b&=\frac i2\left(\vec k_b\otimes\hat\vec{u}_b+\hat\vec{u}_b\otimes\vec k_b\right)&(b\in\integers^d),
\end{align*}

and, from Eq. \eqref{eq:2} (keeping in mind that $\stiffness$ has minor symmetries)

\begin{align*}
\hat\stress_b&=i\left(\stiffness\cdot\vec k_b\right)\cdot\hat\vec{u}_b+\hat\prestress_b&(b\in\integers^d).
\end{align*}

The equilibrium equation \eqref{eq:1} finally gives

\begin{align*}
\vec 0&=\vec k_b\cdot\hat\stress_b=i\left(\vec k_b\cdot\stiffness\cdot\vec k_b\right)\cdot\hat\vec{u}_b+\vec k_b\cdot\hat\prestress_b&(b\in\integers^d).
\end{align*}

The term in brackets $\vec k\cdot\stiffness\cdot\vec k$ is the [[file:./20140131-The_elastic_acoustic_tensor_and_its_inverse.org][acoustic tensor]] associated with the elastic material $\stiffness$, and the above equation is readily solved for the Fourier modes of the displacement

\begin{align*}
\hat\vec{u}_b&=i\left(\vec k_b\cdot\stiffness\cdot\vec k_b\right)^{-1}\cdot\left(\vec k_b\cdot\hat\prestress_b\right)&(b\in\integers^d).
\end{align*}

As a consequence, the Fourier modes of the strain read

\begin{align*}
\hat\strain_b={}&-\frac12\vec k_b\otimes\left(\left(\vec k_b\cdot\stiffness\cdot\vec k_b\right)^{-1}\cdot\left(\vec k_b\cdot\hat\prestress_b\right)\right)\\
&-\frac12\left(\left(\vec k_b\cdot\stiffness\cdot\vec k_b\right)^{-1}\cdot\left(\vec k_b\cdot\hat\prestress_b\right)\right)\otimes\vec k_b&(b\in\integers^d).
\end{align*}

The above expression can be simplified; handling both terms separately, it is successively found

\begin{align*}
\vec k\otimes\left(\left(\vec k\cdot\stiffness\cdot\vec k\right)^{-1}\cdot\left(\vec k\cdot\hat\prestress\right)\right)&=\vec k\otimes\left(\vec k\cdot\hat\prestress\cdot\transpinv{\left(\vec k\cdot\stiffness\cdot\vec k\right)}\right)\\
&=\left(\vec k\otimes\vec k\right)\cdot\hat\prestress\cdot\transpinv{\left(\vec k\cdot\stiffness\cdot\vec k\right)},\\
\left(\left(\vec k\cdot\stiffness\cdot\vec k\right)^{-1}\cdot\left(\vec k\cdot\hat\prestress\right)\right)\otimes\vec k&=\left(\left(\vec k\cdot\stiffness\cdot\vec k\right)^{-1}\cdot\transp{\hat\prestress}\cdot\vec k\right)\otimes\vec k\\
&=\left(\vec k\cdot\stiffness\cdot\vec k\right)^{-1}\cdot\transp{\hat\prestress}\cdot\left(\vec k\otimes\vec k\right),
\end{align*}

and

\begin{align*}
\hat\strain_b={}&-\frac12\left(\vec k_b\otimes\vec k_b\right)\cdot\hat\prestress\cdot\transpinv{\left(\vec k_b\cdot\stiffness\cdot\vec k_b\right)}\\
&-\frac12\left(\vec k_b\cdot\stiffness\cdot\vec k_b\right)^{-1}\cdot\transp{\hat\prestress}\cdot\left(\vec k_b\otimes\vec k_b\right)&(b\in\integers^d).
\end{align*}

Introducing the [[file:./20140226-Decomposition_of_transverse_isotropic_fourth-rank_tensors.org][tensor product of linear transformations]] $\boxtimes$, and recalling that the prestress $\prestress$ is symmetric, the following compact expression can be found

\begin{align*}
\hat\strain_b={}&-\frac12\left(\left(\vec k_b\otimes\vec k_b\right)\boxtimes\left(\vec k_b\cdot\stiffness\cdot\vec k_b\right)^{-1}\right):\hat\prestress_b\\
&-\frac12\left(\left(\vec k_b\cdot\stiffness\cdot\vec k_b\right)^{-1}\boxtimes\left(\vec k_b\otimes\vec k_b\right)\right):\hat\prestress_b&(b\in\integers^d).
\end{align*}

In other words, the Fourier modes of the strain are deduced from the Fourier modes of the prestress by application of a fourth-rank tensor, which can be symmetrized with respect to the last two indices (the prestress being symmetric). It is finally found that

\begin{align*}
\hat\strain_b&=-\hat\tens{\Gamma}(\vec k_b):\hat\prestress_b&(b\in\integers^d),
\end{align*}

where $\hat\tens{\Gamma}$ is the periodic Green operator for strains of the homogeneous material $\stiffness$, defined as follows

\begin{equation}
\label{eq:6}
\hat\tens{\Gamma}(\vec k)=\frac12\left(\left(\vec n\otimes\vec n\right)\boxtimessym\left(\vec n\cdot\stiffness\cdot\vec n\right)^{-1}+\left(\vec n\cdot\stiffness\cdot\vec n\right)^{-1}\boxtimessym\left(\vec n\otimes\vec n\right)\right),
\end{equation}

where $\vec n$ is the direction of the wave-vector $\vec k$, $\vec n=\vec k/\lVert\vec k\rVert$ ($\vec n\otimes\vec n$ is the second-rank projector onto $\vec n$).

* The case of isotropic materials

I have shown in a [[file:./20140131-The_elastic_acoustic_tensor_and_its_inverse.org][previous post]] that in this case, the inverse of the acoustic tensor reads

\begin{equation*}
\left(\vec n\cdot\stiffness\cdot\vec n\right)^{-1}=\frac1\shearmod\left(\frac{1-2\nu}{2\left(1-\nu\right)}\left(\vec n\otimes\vec n\right)+\tens{\delta}-\left(\vec n\otimes\vec n\right)\right)=\frac1\shearmod\tens{\delta}-\frac1{2\shearmod\left(1-\nu\right)}\vec n\otimes\vec n,
\end{equation*}

which leads to the following expression of the periodic Green operator for strains

\begin{equation}
\label{eq:7}
\hat\tens{\Gamma}(\vec k)=\frac1{2\shearmod}\left(\left(\vec n\otimes\vec n\right)\boxtimessym\tens{\delta}+\tens{\delta}\boxtimessym\left(\vec n\otimes\vec n\right)\right)-\frac1{2\shearmod\left(1-\nu\right)}\vec n\otimes\vec n\otimes\vec n\otimes\vec n,
\end{equation}

where the following identity has been used

\begin{equation*}
\left(\vec n\otimes\vec n\right)\boxtimessym\left(\vec n\otimes\vec n\right)=\vec n\otimes\vec n\otimes\vec n\otimes\vec n.
\end{equation*}

The components of $\hat\tens{\Gamma}$ are

\begin{equation}
\label{eq:8}
\hat\gamma_{ijkl}=\frac1{4\shearmod}\left(\delta_{ik}n_jn_l+\delta_{il}n_jn_k+\delta_{jk}n_in_l+\delta_{jl}n_in_k\right)-\frac1{2\shearmod\left(1-\nu\right)}n_in_jn_kn_l.
\end{equation}


* Summary

In a homogeneous, linearly elastic material with stiffness $\stiffness$, the $(L_1,\cdot,L_d)$--periodic prestress $\prestress$ given by

\begin{equation*}
\prestress(\vec x)=\sum_{b\in\integers^d}\hat\prestress_b\exp(i\vec k_b\cdot\vec x)
\end{equation*}

[where $\vec k_b$ is defined by Eq. \eqref{eq:10}] gives rise to the periodic strain

\begin{equation}
\label{eq:9}
\strain(\vec x)=-\sum_{b\in\integers^d}\hat\tens{\Gamma}(\vec k_b):\hat\prestress_b\exp(i\vec k_b\cdot\vec x),
\end{equation}

where $\hat\tens{\Gamma}$ is the periodic Green operator for strains, defined in Fourier space by Eq. \eqref{eq:6}. It should be noted that this expression is valid regardless of the dimension of the physical space, and the material symmetries. If the material is isotropic, the Fourier modes of the Green operator for strains are given by Eqs. \eqref{eq:7} and \eqref{eq:8}, which are valid in both plane strain and 3D elasticity (since the expression of the inverse of the [[file:./20140131-The_elastic_acoustic_tensor_and_its_inverse.org][acoustic tensor]] is).

Finally, it is worth noting that Eq. \eqref{eq:9} is a direct product in Fourier space. Therefore, it is a /convolution product/ in the real space, and we shall write $\strain=-\tens{\Gamma}\ast\prestress$. To the best of my knowledge, though, there is no closed-form expression of $\tens{\Gamma}$ in the real space, and this convenient notation is purely formal.
