# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: Decomposition of transverse isotropic, fourth-rank tensors
#+DATE: <2014-02-26 Wed>
#+LINK: walp1984 https://doi.org/10.1098/rspa.1984.0008

#+BEGIN_ABSTRACT
In [[file:./20140112-Elastic_constants_of_an_isotropic_material-03.org][a previous post]], I introduced the fourth-rank spherical and deviatoric projection tensors. Any isotropic fourth-rank tensor is a linear combination of these two tensors; in other words, the space of isotropic fourth-rank tensors (with minor and major symmetries) is of dimension 2. Similarly, it can be shown ([[walp1984][Walpole, 1984]]) that the space of three-dimensional, /transverse isotropic/ fourth-rank tensors (with minor and major symmetries) is of dimension 6. Furthermore; it is possible to produce a convenient basis of this space. This is the topic of the present post, which is mostly based on the paper by Walpole ([[walp1984][1984]]).
#+END_ABSTRACT

$\newcommand{\kronecker}{\circledast}$

* Two second-rank projection tensors

It is recalled that transverse isotropy is defined by one single preferred direction. In the present post, $\vec n$ denotes the unit vector which indicates this preferred direction. Then, $\tens p$ and $\tens q$ are the following projectors

\begin{equation}
\newcommand{\p}{\tens p}
\newcommand{\q}{\tens q}
\label{eq:1}
\p=\vec n\otimes\vec n,\quad\q=\tens{\delta}-\p.
\end{equation}

$\p$ is the projector onto the direction of anisotropy $\vec n$, while $\q$ is the projection onto the plane of isotropy (orthogonal to $\vec n$). It can readily be verified that

\begin{align*}
\p\cdot\p&=\p,&\q\cdot\q&=\q,&\p\cdot\q&=\q\cdot\p=\tens 0,\\
\p:\p&=1,&\q:\q&=2,&\p:\q&=\q:\p=0.
\end{align*}

* Tensor product of linear transformations

It will be convenient to introduce a new, Kronecker-like product of two second-rank tensors, which Del Piero ([[https://doi.org/10.1007/BF00041097][1979]]) named /tensor product of linear transformations/, and which will be denoted $\boxtimes{}$.

As a preliminary note, it should be observed that any fourth-rank tensor $\tens A$ can be viewed as a endomorphism over the space of second-rank tensors, since $\tens x\mapsto\tens A:\tens x$ is a linear mapping (the convention adopted in this blog for the double dot product has been specified in a [[file:./20140219-On_the_double_dot_product.org][previous post]]). Therefore, the fourth-rank tensor $\tens a\boxtimes\tens b$ ($\tens a, \tens b$: second-rank tensors) can be defined by how it operates on second-rank tensors $\tens x$

\begin{equation}
\label{eq:2}
\left(\tens a\boxtimes\tens b\right):\tens x=\tens a\cdot\tens x\cdot\transp{\tens b}.
\end{equation}

Writing the above definition in terms of the components of $\tens a$, $\tens b$ and $\tens x$, it is found that $\left(\tens a\boxtimes\tens b\right):\tens x=a_{ik}x_{kl}b_{jl}\vec e_i\otimes\vec e_j$, which shows that the components of $\tens a\boxtimes\tens b$ are

\begin{equation}
\label{eq:3}
\left(\tens a\boxtimes\tens b\right)_{ijkl}=a_{ik}b_{jl},
\end{equation}

from which it results

\begin{equation*}
\transp{\left(\tens a\boxtimes\tens b\right)}=\transp{\tens a}\boxtimes\transp{\tens b}.
\end{equation*}

Given four second-rank tensors $\tens a$, $\tens b$, $\tens c$ and $\tens d$, the following identity holds

\begin{equation}
\label{eq:4}
\left(\tens a\boxtimes\tens b\right):\left(\tens c\boxtimes\tens d\right)=\left(\tens a\cdot\tens c\right)\boxtimes\left(\tens b\cdot\tens d\right).
\end{equation}

Indeed, let $\tens x$ be a second-rank tensor. Then, from Eq. \eqref{eq:2}

\begin{align*}
\left(\tens a\boxtimes\tens b\right):\left(\tens c\boxtimes\tens d\right):\tens x&=\left(\tens a\boxtimes\tens b\right):\left(\tens c\cdot\tens x\cdot\transp{\tens d}\right)=\tens a\cdot\left(\tens c\cdot\tens x\cdot\transp{\tens d}\right)\cdot\transp{\tens b}\\
&=\left(\tens a\cdot\tens c\right)\cdot\tens x\cdot\left(\transp{\tens d}\cdot\transp{\tens b}\right)=\left(\tens a\cdot\tens c\right)\cdot\tens x\cdot\transp{\left(\tens b\cdot\tens d\right)}\\
&=\left(\left(\tens a\cdot\tens c\right)\boxtimes\left(\tens b\cdot\tens d\right)\right):\tens x.
\end{align*}

Eq. \eqref{eq:3} shows that even if $\tens a$ and $\tens b$ are symmetric, the tensor product $\tens a\boxtimes\tens b$ does not necessarily have the minor symmetries. It will therefore be convenient to define $\tens a\boxtimessym\tens b$, as the tensor $\tens a\boxtimes\tens b$, /symmetrized with respect to the last two indices/

\begin{equation*}
\left(\tens a\boxtimessym\tens b\right)_{ijkl}=\frac12\left(a_{ik}b_{jl}+a_{il}b_{jk}\right),
\end{equation*}

or, in intrinsic form ($\tens x$: second-rank tensor)

\begin{equation}
\label{eq:5}
\left(\tens a\boxtimessym\tens b\right):\tens x=\frac12\left(\tens a\boxtimes\tens b\right):\left(\tens x+\transp{\tens x}\right)=\frac12\tens a\cdot\left(\tens x+\transp{\tens x}\right)\cdot\transp{\tens b}.
\end{equation}

An identity similar to Eq. \eqref{eq:4} can then be derived with $\boxtimessym$

\begin{equation}
\label{eq:6}
\left(\tens a\boxtimessym\tens b\right):\left(\tens c\boxtimessym\tens d\right)=\frac12\left(\left(\tens a\cdot\tens c\right)\boxtimessym\left(\tens b\cdot\tens d\right)+\left(\tens a\cdot\tens d\right)\boxtimessym\left(\tens b\cdot\tens c\right)\right).
\end{equation}

The following identities, involving the second-rank projectors $\p$ and $\q$ [see Eq. \eqref{eq:1}], readily follow from Eq. \eqref{eq:3}
\begin{align*}
\left(\p\boxtimessym\p\right):\p&=\p, & \left(\p\boxtimessym\p\right):\q&=\tens 0,\\
\left(\q\boxtimessym\q\right):\p&=\tens 0, & \left(\q\boxtimessym\q\right):\q&=\q,
\end{align*}
and
\begin{equation*}
\left(\p\boxtimessym\q\right):\p=\left(\p\boxtimessym\q\right):\q=\left(\q\boxtimessym\p\right):\p=\left(\q\boxtimessym\p\right):\q=\tens 0.
\end{equation*}

Besides, the following multiplication table results from Eq. \eqref{eq:6} $\newcommand{\x}{\boxtimessym}$

#+CAPTION: Multiplication table for the tensors $\p\x\p$, $\p\x\q$, $\q\x\p$ and $\q\x\q$.
#+NAME: tab:1
#+ATTR_HTML: :class center :width 80%
| /        | <           |             |             | >           |
| <c>      | <c>         | <c>         | <c>         | <c>         |
| $:$      | $\p\x\p$    | $\p\x\q$    | $\q\x\p$    | $\q\x\q$    |
|----------+-------------+-------------+-------------+-------------|
| $\p\x\p$ | $\p\x\p$    | $\tens 0$ | $\tens 0$ | $\tens 0$ |
| $\p\x\q$ | $\tens 0$ | $\tens 0$ | $\tens 0$ | $\tens 0$ |
| $\q\x\p$ | $\tens 0$ | $\tens 0$ | $\tens 0$ | $\tens 0$ |
| $\q\x\q$ | $\tens 0$ | $\tens 0$ | $\tens 0$ | $\q\x\q$    |
|----------+-------------+-------------+-------------+-------------|

To conclude, it is observed that the fourth-rank tensor $\tens{I}=\tens{\delta}\boxtimessym\tens{\delta}$ maps any second-rank tensor to its symmetric part: it reduces to the identity tensor over the space of second-rank, symmetric tensors.

* Walpole's basis for transverse isotropic tensors

Walpole ([[walp1984][1984]]) shows that any transverse isotropic tensor is a linear combination of the six fourth-rank tensors $\tens E_1,\tens E_2,\tens E_3,\tens E_4,\tens F,\tens G$ defined as follows

\begin{gather*}
\tens E_1=\p\otimes\p,\quad\tens E_2=\frac12\q\otimes\q,\quad\tens E_3=\frac1{\sqrt2}\p\otimes\q,\quad\tens E_4=\frac1{\sqrt2}\q\otimes\p\\
\tens F=\q\boxtimessym\q-\frac12\q\otimes\q,\quad\tens G=\p\boxtimessym\q+\q\boxtimessym\p.
\end{gather*}

Multiplication (in the sense of the double product) of these tensors is fairly easy, as shown by Table [[tab:2]] below.

#+CAPTION: Multiplication table for the tensors $\tens E_i$, $\tens F$ and $\tens G$ ($i=1,\ldots,4$).$\newcommand{\t}{\tens}$
#+NAME: tab:2
#+ATTR_HTML: :class center :width 50%
| /        | <        |          |          |          |        | >      |
| <c>      | <c>      | <c>      | <c>      | <c>      | <c>    | <c>    |
| $:$      | $\t E_1$ | $\t E_2$ | $\t E_3$ | $\t E_4$ | $\t F$ | $\t G$ |
|----------+----------+----------+----------+----------+--------+--------|
| $\t E_1$ | $\t E_1$ | $\t 0$   | $\t E_3$ | $\t 0$   | $\t 0$ | $\t 0$ |
| $\t E_2$ | $\t 0$   | $\t E_2$ | $\t 0$   | $\t E_4$ | $\t 0$ | $\t 0$ |
| $\t E_3$ | $\t 0$   | $\t E_3$ | $\t 0$   | $\t E_1$ | $\t 0$ | $\t 0$ |
| $\t E_4$ | $\t E_4$ | $\t 0$   | $\t E_2$ | $\t 0$   | $\t 0$ | $\t 0$ |
| $\t F$   | $\t 0$   | $\t 0$   | $\t 0$   | $\t 0$   | $\t F$ | $\t 0$ |
| $\t G$   | $\t 0$   | $\t 0$   | $\t 0$   | $\t 0$   | $\t 0$ | $\t G$ |

 The above table must be read as: "row double dot column equals cell". For example, $\tens E_1:\tens E_3=\tens E_3$ and $\tens E_3:\tens E_1=\tens 0$.

* A convenient representation of transverse isotropic, fourth-rank tensors

Walpole ([[walp1984][1984]]) proposes a convenient representation of any transverse isotropic tensor $\tens T$, as the triplet $(A, f, g)$ where $A$ is a 2 × 2 matrix and $f$ and $g$ are two scalars. This representation should be understood as

\begin{equation*}
\tens T=a_{11}\tens E_1+a_{22}\tens E_2+a_{12}\tens E_3+a_{21}\tens E_4+f\tens F+g\tens G,
\end{equation*}

where $a_{ij}$ are the coefficients of $A$. The condensed notation $\tens T=(A, f, g)$ shall be adopted. Using the multiplication table [[tab:2]], it can readily be verified that if $\tens T=(A, f, g)$ and $\tens T'=(A', f', g')$, then

\begin{equation*}
\tens T:\tens T'=(A\cdot A', ff', gg').
\end{equation*}

This representation is particularly convenient when it comes to inverting transverse isotropic tensors. Indeed,

\begin{equation*}
\tens T^{-1}=(A^{-1}, 1/f, 1/g).
\end{equation*}

Transposition is also straightforward

\begin{equation*}
\transp{\tens T}=(\transp{A}, f, g).
\end{equation*}

* Decomposition of fourth-rank, isotropic tensors in Walpole's basis

The isotropic tensors $\tens{I}$, $\tens{J}$ and $\tens{K}$ introduced [[file:./20140112-Elastic_constants_of_an_isotropic_material-03.org][previously]] can be considered as transverse isotropic tensors. As such, they can be decomposed in Walpole's basis. First, the identity tensor $\tens{I}$ decomposes as follows

\begin{align*}
\tens{I}&=\tens{\delta}\boxtimessym\tens{\delta}=\left(\p+\q\right)\boxtimessym\left(\p+\q\right)\\
&=\p\boxtimessym\p+\p\boxtimessym\q+\q\boxtimessym\p+\q\boxtimessym\q\\
&=\tens E_1+\tens G+\tens F+\tens E_2.
\end{align*}

where the identity $\p\boxtimessym\p=\p\otimes\p=\tens E_1$ has been used. Now, the decomposition of $\tens{J}$ is readily derived from its definition

\begin{align*}
3\tens{J}&=\tens{\delta}\otimes\tens{\delta}=\left(\p+\q\right)\otimes\left(\p+\q\right)\\
&=\p\otimes\p+\p\otimes\q+\q\otimes\p+\q\otimes\q\\
&=\tens E_1+\sqrt2\tens E_3+\sqrt2\tens E_4+2\tens E_2.
\end{align*}

Finally, the decomposition of the deviatoric projection tensor $\tens{K}$ is found from the definition $\tens{K}=\tens{I}-\tens{J}$. To sum up

\begin{gather*}
\tens{I}=\left(\begin{bmatrix}1&0\\0&1\end{bmatrix}, 1, 1\right),\\
\tens{J}=\left(\frac13\begin{bmatrix}1&\sqrt2\\\sqrt2&2\end{bmatrix}, 0, 0\right),\\
\tens{K}=\left(\frac13\begin{bmatrix}2&-\sqrt2\\-\sqrt2&1\end{bmatrix}, 1, 1\right).
\end{gather*}

* Conclusion

In the present post, a convenient decomposition of three-dimensional, fourth-rank, transverse isotropic tensors as a linear combination of six basis tensors has been proposed. Multiplication (in the sense of the [[file:./20140219-On_the_double_dot_product.org][double dot product]]) of these basis tensors is straightforward (see Table [[tab:2]]). Besides, representing transverse isotropic tensors as a (matrix, scalar, scalar) triplet eases their multiplication and inversion. Walpole's basis turns out to be very handy in many situations (including the derivation of the Green operator for strains).
