# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: When a thin shell is not so thin, part\nbsp{}3: the thick shell solution
#+DATE: [2015-07-06 Mon]

Finding the stress resultant and stress couple in a spherical pressure vessel seems easy enough. Well, this apparently simple problem allows us to highlight subtle thickness effects within shells. It should be emphasized again that these thickness effects have nothing to do with shear corrections. Indeed, shear stresses are null at any point of the spherical pressure vessel. Rather, the thickness effects we are discussing in this series are due to curvature.

In the [[file:./20150608-When_a_thin_shell_is_not_so_thin-01.org][first instalment]] of this series, I showed that using Koiter's thin shell solution leads to a non-null stress couple, which came as quite a surprise. In the [[file:./20150701-When_a_thin_shell_is_not_so_thin-02.org][second instalment]], I used the exact, 3D solution to derive reference values of the stress couple and stress resultant through integration over the thickness of the shell. In particular, I showed that thickness corrections /had/ to be incorporated.

This still does not settle the matter, since the results obtained within the framework of Koiter's thin shell theory (see [[file:./20150608-When_a_thin_shell_is_not_so_thin-01.org][first instalment]]) are inconsistent with the reference, 3D elasticity values (see [[file:./20150701-When_a_thin_shell_is_not_so_thin-02.org][second instalment]]). To reconcile both approaches (3D elasticity vs. shell theory), we need to use a /thick/ shell theory, as illustrated below.

* Strain distribution in the spherical pressure vessel

The fundamental assumption of all shell theories is that displacement of any point of the shell is completely defined by the rigid body motion (translation and rotation) of its projection onto the base surface. In the present case, owing to the symmetries of the problem, points of the base surface move along the normal $\mathbf n$

\begin{equation}
\label{eq:1}\mathbf u = w\mathbf n,
\end{equation}

where $w$ is the normal displacement, which is constant over the base surface. Since the rotation is null, all points (across the thickness of the shell) have the same normal displacement. Therefore, Eq. \eqref{eq:1} defines the 3D displacement field within the shell, seen as a 3D continuum. From this 3D displacement field, we can readily derive the corresponding strain field. We will use a simplified, geometric approach, rather than the general formulas in spherical coordinates. This is possible because there are so many symmetries in the problem at hand!

The in-plane strain $\epsilon$ at the distance $r$ of the center is given by the relative change of length of the equator

\begin{equation}
\label{eq:2}\epsilon=\frac{2\pi\left(r+w\right)-2\pi r}{2\pi r}=\frac wr.
\end{equation}

In the [[file:./20150608-When_a_thin_shell_is_not_so_thin-01.org][first instalment]], we found $\epsilon=w/R$, where $R$ is the radius of the midsurface. Eq. \eqref{eq:2} therefore incorporates thickness corrections which we previously overlooked.

* Stress distribution in the spherical pressure vessel

Stresses in the spherical pressure vessel are derived from the strains [see Eq. \eqref{eq:2}], within the framework of plane stress elasticity

# \begin{subequations}
\begin{align}
\label{eq:3}\sigma_{\theta\theta}&=\frac E{1-\nu^2}\left(\epsilon_{\theta\theta}+\nu\epsilon_{\phi\phi}\right)\\
\label{eq:4}\sigma_{\phi\phi}&=\frac E{1-\nu^2}\left(\epsilon_{\phi\phi}+\nu\epsilon_{\theta\theta}\right).
\end{align}
# \end{subequations}

Since the solution is isotropic ($\epsilon_{\theta\theta}=\epsilon_{\phi\phi}=\epsilon$ and $\sigma_{\theta\theta}=\sigma_{\phi\phi}=\sigma$), Eqs. \eqref{eq:3} and \eqref{eq:4} lead to

\begin{equation}
\label{eq:5}\sigma=\frac E{1-\nu}\epsilon=\frac E{1-\nu}\frac wr.
\end{equation}

* Stress resultant and stress couple

Eq. \eqref{eq:5} is finally integrated over the thickness of the shell to obtain the stress resultant and stress couple. Integration must include thickness corrections, which amount to a $r/R$ factor within the integral (see [[file:./20150701-When_a_thin_shell_is_not_so_thin-02.org][previous instalment]] of this series).

\begin{align}
\label{eq:6}N&=\int_{R_\mathrm{int}}^{R_\mathrm{ext}}\sigma(r)\,\frac rR\,\mathrm{d}r=\frac{Eh}{1-\nu}\frac wR,\\
\label{eq:7}M&=\int_{R_\mathrm{int}}^{R_\mathrm{ext}}-\left(r-R\right)\sigma(r)\,\frac rR\,\mathrm{d}r=0.
\end{align}

Now, things start getting really interesting! Indeed, in the thick shell approach, the stress couple is (as expected) rigorously null! Since $M=0$, it can readily be deduced that

\begin{equation}
\label{eq:8}N=\frac{pR}2.
\end{equation}

In other words, the classical formula is retrieved (see [[http://en.wikipedia.org/wiki/Pressure_vessel#Stress_in_thin-walled_pressure_vessels][Wikipedia]]).

* Conclusion

In the present post, we finally resolved all contradictions regarding the computation of stress resultant and stress couple within a spherical pressure vessel. In the discussion below, $\eta$ denotes the slenderness of the shell, $\eta=h/R$. Besides, by "k-th order terms", we mean terms of order $\eta^k$.

Four difference approaches can be followed to analyse the equilibrium of a spherical pressure vessel (see Tab. [[tab:1]] for a summary). In the classical membrane approach, stress couples are overlooked, and the classical formula $N=pR/2$ is obtained.

In the thin shell approach, the stress resultant deviates slightly from this classical value (by second order terms) and the stress couple is /not/ null (rather, it is of second order).

In the thick shell approach, the stress couple is rigorously null and the classical formula is retrieved for the stress resultant. Thickness corrections appear in two different places

  1. in the strain distribution across the thickness of the shell [see Eq. \eqref{eq:2}]: the distribution is hyperbolic with respect to the thickness coordinate,
  2. in the stress-stress resultant and stress-stress couple integral relations [see Eqs. \eqref{eq:6} and \eqref{eq:7}].

In the 3D approach, the true stress resultant differs from $N=pR/2$ by second order terms, while the true stress couple is of fourth order.

What should we deduce from this study? Obviously, beware thin shell theories! Fortunately, I believe that most FE codes implement the thick shell theory. More fundamentally, I am still trying to understand what these results really imply. Does that mean that the asymptotic convergence (as the thickness tends to zero) of thick shell models is faster than that of thin shell models? That is something I am going to investigate.

This closes our series on thick shells. I hope you enjoyed reading it... and maybe learned something! Should you want to dig deeper into various thick shell theories, do start with Leissa ([[https://ntrs.nasa.gov/search.jsp?R=19730018197][1973]]), who gives a good overview.

#+CAPTION: Comparison of three different approaches for the analysis of the spherical pressure vessel
#+NAME: tab:1
#+ATTR_HTML: :rules groups :frame hsides :border 2 :cellpadding 6 :cellspacing 0
| <l>                                    | <c>             | <c>               | <c>                |
|                                        | Exact 3D theory | Thin shell theory | Thick shell theory |
|----------------------------------------+-----------------+-------------------+--------------------|
| Stress resultant (deviation from pR/2) | \eta^2          | \eta^2            | 0                  |
| Stress couple                          | \eta^4          | \eta^2            | 0                  |
|----------------------------------------+-----------------+-------------------+--------------------|
