# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+TITLE: New paper out!
#+DATE: [2017-02-23 Thu]

My paper “Towards improved Hashin--Shtrikman bounds on the effective moduli of random composites” has recently been published in /Mechanics & Industry/. The abstract is reproduced below

#+BEGIN_QUOTE
The celebrated bounds of Hashin and Shtrikman on the effective properties of composites are valid for a very wide class of materials. However, they incorporate only a very limited amount of information on the microstructure (volume fraction of each phase in the case of isotropic microstructures). As a result, they are generally not tight. In this work, we present an attempt at improving these bounds by incorporating explicitly the local volume fraction to the set of local descriptors of the microstructure. We show that, quite unexpectedly, the process fails in the sense that the classical bounds are retrieved. We further show that this negative result applies to so-called weakly isotropic local descriptors of the microstructure (to be defined in this paper). This suggests that improved bounds may be obtained with anisotropic descriptors.
#+END_QUOTE

The post-print is available on [[https://hal-enpc.archives-ouvertes.fr/hal-01474668][HAL ENPC]] and the published version is available [[https://doi.org/10.1051/meca/2016037][here]].
