# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/css-1.org"
#+TITLE: New paper on Discrete Digital Projections Correlation
#+DATE: [2017-04-26 Wed]

Our paper “Discrete Digital Projections Correlation: a
reconstruction-free method to quantify local kinematics in granular
media by X-ray tomography” has recently been published in
/Experimental Mechanics/. The abstract is reproduced below

#+BEGIN_QUOTE
We propose a new method to measure the translations and rotations of
each individual grain in a granular material imaged by computerized
tomography. Unlike the classic approach, which requires that both
initial and current configurations be fully reconstructed, ours only
requires a reconstruction of the initial configuration. In this sense,
our method is reconstruction-free, since any subsequent deformed state
can be analyzed without further reconstruction. One distinguishing
feature of the proposed method is that it requires very few
projections of the deformed sample, thus allowing for time-resolved
experiments.
#+END_QUOTE

The preprint is available on [[https://hal-enpc.archives-ouvertes.fr/hal-01474701][HAL]] (see also below) and the published
version is available [[https://doi.org/10.1007/s11340-017-0263-5][here]].

#+BEGIN_EXPORT html
<embed width="100%" height="600" src="https://hal-enpc.archives-ouvertes.fr/hal-01474701/file/D-DPC-Pre-print.pdf" type="application/pdf" />
#+END_EXPORT
