# -*- coding: utf-8; -*-
#+SETUPFILE: "../header.org"
#+SETUPFILE: "../header-1.org"
#+INCLUDE: "../navbar-1.org"
#+TITLE: Scientific computing under Windows 7, part 5: LAMMPS
#+DATE: <2013-10-06 Sun>

From the [[http://lammps.sandia.gov/index.html][official website]]

#+BEGIN_QUOTE
LAMMPS is a classical molecular dynamics code, and an acronym for Large-scale Atomic/Molecular Massively Parallel Simulator.
#+END_QUOTE

To install from sources, download the [[http://lammps.sandia.gov/download.html#tar][tarball]]. Extract it in e.g. =C:\src\lammps-30Sep13= (your version of LAMMPS might differ). Edit the file =C:\src\lammps-30Sep13\src\Makefile=, and replace the following line

#+BEGIN_EXAMPLE
  EXE =       $(ROOT)_$@
#+END_EXAMPLE

with

#+BEGIN_EXAMPLE
  EXE =       $(ROOT)_$@.exe
#+END_EXAMPLE

Then create an appropriate =Makefile.mingw32=, starting from =Makefile.serial=. In the MSYS console::

#+BEGIN_EXAMPLE
  $ cd /C/src/lammps-30Sep13/src/MAKE
  $ cp Makefile.serial Makefile.mingw32
#+END_EXAMPLE

If you want to link LAMMPS against FFTW (which you must first install, see a previous post), edit the newly created file and modify the lines relating to FFT

#+BEGIN_EXAMPLE
  FFT_INC = -DFFT_FFTW3 -I/mingw/include
  FFT_PATH = -L/mingw/lib
  FFT_LIB = -lfftw3
#+END_EXAMPLE

(assuming you have installed the static version of the library). Before you compile LAMMPS itself, you need to compile the MPI stubs, which is a dummy (serial) replacement for a true MPI library. This should normally be done by =make stubs=, but this last command somehow does not work

#+BEGIN_EXAMPLE
  $ cd /C/src/lammps-30Sep13/src
  make: `stubs' is up to date.
#+END_EXAMPLE

The solution is to force compilation of the stubs::

#+BEGIN_EXAMPLE
  $ cd /C/src/lammps-30Sep13/src/STUBS
  $ make
#+END_EXAMPLE

which produces a file =libmpi_stubs.a=. You are now ready to compile::

#+BEGIN_EXAMPLE
  $ cd /C/src/lammps-30Sep13/src
  $ make mingw32
#+END_EXAMPLE

which produces an executable =src/lmp_mingw32.exe=. To test this executable, go to the =examples= directory::

#+BEGIN_EXAMPLE
  $ cd /C/src/lammps-30Sep13/examples
#+END_EXAMPLE

and run one of the applications, for example::

#+BEGIN_EXAMPLE
  $ cd micelle
  $ ../../src/lmp_mingw32.exe < in.micelle
#+END_EXAMPLE
