# -*- coding: utf-8; -*-
#+SETUPFILE: "../header.org"
#+SETUPFILE: "../header-1.org"
#+TITLE: Elastic constants of an isotropic material, part 1: 3D elasticity

Among all classes of materials, the class of linearly elastic and isotropic materials is probably the simplest. Such materials are defined by two elastic constants: for example, Young's modulus $E$ and Poisson's ratio $\nu$. However, depending on the situation, this pair of constants might not be the most appropriate@@html:<!-- more -->@@ (meaning that they may not lead to the most compact expressions). Alternative sets of elastic constants are

- Lamé's constants $\lambda$ and $\shearmod$,
- bulk and shear moduli $\bulkmod$ and $\shearmod$,
- shear modulus and Poisson ratio $\shearmod$ and $\nu$.

Each pair of constants is of course strictly equivalent to any other. I tend to work primarily with $\shearmod$ and $\nu$, and always find myself looking for the expression of E, $\lambda$ and $\bulkmod$ as a function of $\shearmod$ and $\nu$. In this series, we will derive these expressions, starting with 3D elasticity.

* Lamé's constants

The constitutive equation of a linearly elastic and isotropic material reads
\begin{equation}
    \label{eq:1}
    \stresscomp_{ij} = \lambda\straincomp_{kk}\delta_{ij} + 2\shearmod\straincomp_{ij}
\end{equation}

where $\stresscomp_{ij}$ (resp. $\straincomp_{ij}$) denotes the stress (resp. strain) tensor, while $\lambda$ (resp. $\shearmod$) is Lamé's first (resp. second) constant; $\shearmod$ is also called the /shear modulus/. Eq. \eqref{eq:1} is inverted so as to express the strain tensor as a function of the stress tensor. Taking $i = j$ and summing over repeated indices, we find
\begin{equation*}
    \stresscomp_{ii} = (3\lambda + 2\shearmod)\straincomp_{kk},
\end{equation*}

where it is recalled that $\delta_{ii} = 3$ (the dimension of the physical space). Plugging into Eq. \eqref{eq:1}
\begin{equation*}
    \stresscomp_{ij} = \frac{\lambda}{3\lambda+2\shearmod}\stresscomp_{kk}\delta_{ij} + 2\shearmod\straincomp_{ij}
\end{equation*}

and finally
\begin{equation}
    \label{eq:2}
    \straincomp_{ij} = \frac{\stresscomp_{ij}}{2\shearmod} - \frac{\lambda}{2\shearmod(3\lambda+2\shearmod)}\stresscomp_{kk}\delta_{ij}.
\end{equation}

* Young's modulus and Poisson ratio

We consider a uniaxial traction experiment, where the stress tensor reduces to $\stresscomp\vec e_3\otimes\vec e_3$ ($\stresscomp$ is the imposed uniaxial stress). Substitution in Eq. \eqref{eq:2} leads to the following expression of the longitudinal strain
\begin{equation*}
    \straincomp_{33} = \frac{\lambda+\shearmod}{\shearmod(3\lambda+2\shearmod)}\stresscomp.
\end{equation*}

By definition, Young's modulus is the longitudinal stress to longitudinal strain ratio: $E=\stresscomp/\straincomp_{33}$, so that
\begin{equation}
    \label{eq:3}
    E = \frac{\shearmod(3\lambda+2\shearmod)}{\lambda+\shearmod}.
\end{equation}

The expression of the transverse strains is again derived using Eq. \eqref{eq:2}
\begin{equation*}
    \straincomp_{11} = \straincomp_{22} = -\frac{\lambda}{2\shearmod(3\lambda+2\shearmod)}
\end{equation*}

and by definition, Poisson's ratio is the oposite of the transverse to longitudinal strain ratio
\begin{equation}
    \label{eq:4}
    \nu = -\frac{\straincomp_{11}}{\straincomp_{33}} = -\frac{\straincomp_{22}}{\straincomp_{33}} = \frac{\lambda}{2(\lambda+\shearmod)}.
\end{equation}

Expressions \eqref{eq:3} and \eqref{eq:4} can be substituted in the constitutive equation \eqref{eq:2}, leading to
\begin{equation}
    \label{eq:5}
    \straincomp_{ij} = \frac{1+\nu}E\stresscomp_{ij} - \frac\nu E\stresscomp_{kk}\delta_{ij}.
\end{equation}

* Bulk and shear moduli

We now consider an isotropic compression experiment, where the stress tensor reduces to a hydrostatic pressure $\stresscomp_{ij}=-p\delta_{ij}$. Using Eq. \eqref{eq:1}, we find that the strain tensor is also isotropic
\begin{equation}
    \label{eq:6}
    \straincomp_{ij} = -\frac{p\delta_{ij}}{3\lambda+2\shearmod}.
\end{equation}

It is recalled that $\straincomp_\text v=\straincomp_{kk} / 3$ denotes the relative volume change of the material. Then, from Eq. \eqref{eq:6}
\begin{equation*}
    \straincomp_\text v = -\frac p{\bulkmod_\text{3D}},
\end{equation*}

where $\bulkmod_\text{3D}$ denotes the bulk modulus, defined as follows
\begin{equation}
    \label{eq:7}
    \bulkmod_\text{3D} = \lambda + \frac 23\shearmod.
\end{equation}

As we shall see in the [[file:./20131229-Elastic_constants_of_an_isotropic_material-02.org][next instalment]] of this series, the definition of the bulk modulus /depends on the dimension of the physical space/, hence the '3D' subscript. Using $\bulkmod$ and $\shearmod$ as elastic constants, Eq. \eqref{eq:1} reads
\begin{equation}
    \label{eq:8}
    \stresscomp_{ij} = \bulkmod_\text{3D}\straincomp_{kk}\delta_{ij}+2\shearmod\left(\straincomp_{ij}-\frac{\straincomp_{kk}}3\delta_{ij}\right)
\end{equation}

* Shear modulus and Poisson ratio

I quite often use the shear modulus $\shearmod$ and Poisson ratio $\nu$ as the constants defining the elastic material. One of the reasons for this is the fact that the components of the fourth-rank Green operator for strains have the same expression in 3D and 2D (plane strain) elasticity when expressed as a function of $\shearmod$ and $\nu$.

In the present section, all other elastic constants are expressed as functions of these two constants. First, from Eq. \eqref{eq:4}, it is readily found that
\begin{equation}
    \label{eq:9}
    \lambda = \frac{2\shearmod\nu}{1-2\nu}.
\end{equation}

Then, combining Eqs. \eqref{eq:3} and \eqref{eq:4}
\begin{equation*}
    E = 2\shearmod(1+\nu).
\end{equation*}

Finally, from Eqs. \eqref{eq:7} and \eqref{eq:9}
\begin{equation*}
    \bulkmod_\text{3D} = \frac23\frac{1+\nu}{1-2\nu}\shearmod.
\end{equation*}

* Conclusion

In this instalment, we have defined Lamé's first and second constants, Young's modulus, Poisson's ratio, as well as the (3D) bulk modulus. Expressions relating these various constants have also been derived. In the [[file:./20131229-Elastic_constants_of_an_isotropic_material-02.org][next instalment]] of this series, we will discuss the case of 2D (plane strain elasticity).
