# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: When a thin shell is not so thin, part\nbsp{}2: the 3D, exact solution
#+DATE: [2015-06-10 Wed]

In the [[file:./20150608-When_a_thin_shell_is_not_so_thin-01.org][previous instalment]] of this series, we analysed a spherical pressure vessel by means of Koiter's linear theory of thin shells. We found the somewhat unexpected result that the stress couple was not null. Besides, we also found that the stress resultant was slightly different from the well-known value \(N=pR/2\). So what was wrong with the previous analysis? To explore this question, we will make use of the exact solution in 3D elasticity.

* The spherical pressure vessel, exact solution

Finding the stresses and displacements in a pressure vessel is a classical exercise in 3D linear elasticity. In this post, I will spare you the details of the derivation (which can be found in e.g. XXX). Instead, I will come straight to the point, and provide you with the exact expression of the stress tensor in spherical coordinates (\(r\): distance to the center of the spherical pressure vessel)

\begin{gather}
\label{eq:1}\sigma_{rr}=A-\frac{2B}{r^3},\\
\label{eq:2}\sigma_{\theta\theta}=\sigma_{\phi\phi}=A+\frac{B}{r^3},
\end{gather}

all other components being null. The integration constants \(A\) and \(B\) are defined below

\begin{align}
A&=-\frac{p_\text{ext}R_\text{ext}^3-p_\text{int}R_\text{int}^3}{R_\text{ext}^3-R_\text{int}^3},\\
B&=-\frac12\frac{\left(p_\text{ext}-p_\text{int}\right)R_\text{int}^3R_\text{ext}^3}{R_\text{ext}^3-R_\text{int}^3},\\
\end{align}

where \(R_\text{int}\) and \(R_\text{ext}\) denote the internal and external radii of the spherical pressure vessel; \(p_\text{int}\) and \(p_\text{ext}\) denote the internal and external pressures. In the remainder of this post, \(\sigma\) will denote the common value of the in-plane stresses

\begin{equation}
\sigma=\sigma_{\theta\theta}=\sigma_{\phi\phi}.
\end{equation}

From Eq. \eqref{eq:2}, we readily find the following expressions of the stress resultant \(N=N_{\theta\theta}=N_{\phi\phi}\) and stress couple \(M=M_{\theta\theta}=M_{\phi\phi}\)

\begin{align}
N &= \int_{R_\text{int}}^{R_\text{ext}}\sigma\,\mathrm{d}r,\\
M &= -\int_{R_\text{int}}^{R_\text{ext}}\left(r-R\right)\sigma\,\mathrm{d}r.
\end{align}
