# -*- coding: utf-8; fill-column: 79 -*-
#+SETUPFILE: "../include/css-1.org"
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: On the periodic-plus-smooth decomposition of an image, part 3: the energy as a quadratic form
#+DATE: [2018-01-15 Mon]
#+LINK: moisan2011   https://doi.org/10.1007/s10851-010-0227-1
#+LINK: sb-blog-prev ./On_the_periodic-plus-smooth_decomposition_of_an_image-02.org
#+LINK: sb-blog-next ./On_the_periodic-plus-smooth_decomposition_of_an_image-04.org
#+LINK: sb-blog-data-dir ./On_the_periodic-plus-smooth_decomposition_of_an_image/
#+PROPERTY: header-args:ipython :session :eval no-export :exports both

In the [[sb-blog-prev:][previous instalment]] of this series, we introduced the
periodic-plus-smooth decomposition of an image as a pair of images which
minimizes an energy functional. The purpose of this post is to show that this
energy is in fact a quadratic functional, the minimization of which therefore
amounts to solving a linear problem.

In this post, it will be convenient to regard images as vectors. Given two
$m\times n$ images $u$ and $v$, the scalar product $u\cdot v$ is then defined
as
\begin{equation*}
u\cdot v=\sum_{i=0}^{m-1}\sum_{j=0}^{n-1}u_{ij}v_{ij}.
\end{equation*}

Likewise, a linear operator $A$ over the space of $m\times n$ images is defined
as follows
\begin{equation*}
v=A\cdot u,\quad\text{with}\quad v_{ij}
=\sum_{k=0}^{m-1}\sum_{l=0}^{n-1}A_{ij,kl}u_{kl}.
\end{equation*}

According to Moisan ([[moisan2011:][2011]]), the total energy $E(p, s)$ of the
periodic-plus-smooth decomposition of an image $u=p+s$ is defined as the sum
$E(p, s)=E_\mathrm p(p)+E_\mathrm s(s)$. The contributions $E_\mathrm p(p)$ of
the [[periodic-contrib][periodic component]] and $E_\mathrm s(s)$] of the [[smooth-contrib][smooth component]] $s$ to the
total energy $E$ are analyzed separately below.

* Contribution of the periodic component <<periodic-contrib>>

The contribution to the total energy of the periodic component $p$ is defined
by Moisan ([[moisan2011:][2011]]) as follows (see also [[sb-blog-prev:][previous post]])
\begin{equation}
\label{eq:1}
E_\mathrm p(p)=2\sum_{i=0}^{m-1}(p_{i, n-1}-p_{i, 0})^2
+2\sum_{j=0}^{n-1}(p_{m-1, j}-p_{0, j})^2.\\
\end{equation}

In order to transform the first term, we observe that, $u$ and $v$ being two
$m\times n$ images

\begin{equation}
\begin{aligned}
\sum_{i=0}^{m-1}(u_{i, n-1}-u_{i, 0})(v_{i, n-1}-v_{i, 0})
&=\sum_{i=0}^{m-1}u_{i, 0}(v_{i, 0}-v_{i, n-1})
+\sum_{i=0}^{m-1}u_{i, n-1}(v_{i, n-1}-v_{i, 0})\\
&=\tfrac12 u\cdot(A_\mathrm h\cdot v),
\end{aligned}
\label{eq:2}
\end{equation}

where we have introduced the linear operator $A_\mathrm h$ defined as follows

\begin{equation}
\tfrac12(A_\mathrm h\cdot u)_{ij}=
\begin{cases}
u_{i, 0}-u_{i, n-1} & \text{if }j=0,\\
u_{i, n-1}-u_{i, 0} & \text{if }j=n-1,\\
0                   & \text{otherwise}.
\end{cases}
\label{eq:3}
\end{equation}

From the left-hand side of Eq. \eqref{eq:2}, the linear operator $A_\mathrm h$
thus defined is obviously symmetric and positive. Besides, the first term in Eq.
\eqref{eq:1} reads

\begin{equation*}
2\sum_{i=0}^{m-1}(p_{i, n-1}-p_{i, 0})^2=p\cdot A_\mathrm h\cdot p.
\end{equation*}

Turning now to the second term in Eq. \eqref{eq:1}, we introduce the symmetric,
positive linear operator $A_\mathrm v$ defined by

\begin{equation}
\tfrac12(A_\mathrm v\cdot u)_{ij}=\begin{cases}
u_{0, j}-u_{m-1, j} & \text{if }i=0,\\
u_{m-1, j}-u_{0, j} & \text{if }i=m-1,\\
0                   & \text{otherwise},
\end{cases}
\label{eq:4}
\end{equation}

so that

\begin{equation*}
2\sum_{j=0}^{n-1}(p_{m-1, j}-p_{0, j})^2=p\cdot A_\mathrm v\cdot p.
\end{equation*}

Gathering the above results and introducing the symmetric operator $A=A_\mathrm
h+A_\mathrm v$, we finally find that $E_\mathrm p(p)=p\cdot A\cdot p$.

* Contribution of the smooth component <<smooth-contrib>>

The contribution to the total energy of the smooth component $s$ is defined by
Moisan ([[moisan2011:][2011]]) as follows (see also [[sb-blog-prev:][previous post]])

\begin{equation}
\label{eq:5}
E_\mathrm s(s)=2\sum_{i=0}^{m-2}\sum_{j=0}^{n-1}(s_{i+1, j}-s_{i, j})^2
+2\sum_{i=0}^{m-1}\sum_{j=0}^{n-2}(s_{i, j+1}-s_{i, j})^2.
\end{equation}

In order to transform the first term, we observe that, $u$ and $v$ being two
$m\times n$ images
\begin{equation}
\begin{aligned}[b]
&\sum_{i=0}^{m-2}\sum_{j=0}^{n-1}(u_{i+1, j}-u_{i, j})(v_{i+1, j}-v_{i, j})\\
={}&\sum_{i=0}^{m-2}\sum_{j=0}^{n-1}u_{i+1, j}(v_{i+1, j}-v_{i, j})
-\sum_{i=0}^{m-2}\sum_{j=0}^{n-1}u_{i, j}(v_{i+1, j}-v_{i, j})\\
={}&\sum_{i=1}^{m-1}\sum_{j=0}^{n-1}u_{i, j}(v_{i, j}-v_{i-1, j})
-\sum_{i=0}^{m-2}\sum_{j=0}^{n-1}u_{i, j}(v_{i+1, j}-v_{i, j})\\
={}&\sum_{i=1}^{m-2}\sum_{j=0}^{n-1}u_{i, j}(2v_{i, j}-v_{i-1, j}-v_{i+1,j})\\
&+\sum_{j=0}^{n-1}u_{m-1, j}(v_{m-1, j}-v_{m-2, j})
+\sum_{j=0}^{n-1}u_{0, j}(v_{0, j}-v_{1, j})\\
={}&\tfrac12 u\cdot(B_\mathrm h\cdot v),
\end{aligned}
\label{eq:6}
\end{equation}

where we have introduced the linear operator $B_\mathrm h$ defined as follows

\begin{equation}
\tfrac12(B_\mathrm h\cdot u)_{i,j}=
\begin{cases}
u_{0, j}-u_{1, j}              & \text{if }i=0,\\
u_{m-1, j}-u_{m-2, j}          & \text{if }i=m-1,\\
2u_{i, j}-u_{i-1, j}-u_{i+1,j} & \text{otherwise}.
\end{cases}
\label{eq:7}
\end{equation}

From the left-hand side of Eq. \eqref{eq:6}, the linear operator $B_\mathrm h$
thus defined is obviously symmetric and positive. Besides, the first term in Eq.
\eqref{eq:5} reads

\begin{equation*}
2\sum_{i=0}^{m-2}\sum_{j=0}^{n-1}(s_{i+1, j}-s_{i, j})^2
=s\cdot B_\mathrm h\cdot s.
\end{equation*}

Turning now to the second term in Eq. \eqref{eq:5}, we introduce the symmetric,
positive linear operator $B_\mathrm v$ defined by

\begin{equation}
\tfrac12(B_\mathrm v\cdot u)_{i,j}=
\begin{cases}
u_{i, 0}-u_{i, 1}              & \text{if }j=0,\\
u_{i, n-1}-u_{i, n-2}          & \text{if }j=n-1,\\
2u_{i, j}-u_{i, j-1}-u_{i,j+1} & \text{otherwise}.
\end{cases}
\label{eq:8}
\end{equation}

so that

\begin{equation*}
2\sum_{i=0}^{m-1}\sum_{j=0}^{n-2}(s_{i, j+1}-s_{i, j})^2
=s\cdot B_\mathrm v\cdot s.
\end{equation*}

Gathering the above results and introducing the symmetric, positive operator $B=B_\mathrm
h+B_\mathrm v$, we finally find that $E_\mathrm s(s)=s\cdot B\cdot s$.
