# -*- coding: utf-8; -*-
#+SETUPFILE: "../include/mathjax.org"
#+TITLE: Orientation correlations among rice grains, part 5: thresholding
#+DATE: [2015-07-08 Wed]
#+PROPERTY: header-args:python :results value verbatim :session :exports both

* Otsu's method

Otsu's method ([[file:../pages/references.org::#LEIS1979][Otsu, 1979]]) is a popular thresholding method. It quite effective on simple images, when the histogram has two well separated peaks. Otsu's otimum threshold is often presented as (quoted from [[https://en.wikipedia.org/wiki/Otsu%27s_method][Wikipedia]])

#+BEGIN_QUOTE
separating the two classes so that their combined spread (intra-class variance) is minimal, or equivalently (because the sum of pairwise squared distances is constant), so that their inter-class variance is maximal.
#+END_QUOTE

While this is a very precise definition (and Otsu's original paper is extremely clear), it has always puzzled me as non-intuitive. Why should maximising the intra-class variance return a satisfactorily thresholded image? Well, I came to develop my own view on Otsu's method, which I will present in this section.

We start with the original (noisy) image, which will be considered as a map $f\colon E\to\{0,\ldots,L-1\}$ from the set $E$ of pixels to the set $\{0,\ldots,L-1\}$ of gray levels ($L$ denotes the total number of grey levels).

We want to find the "best" binary approximation of $f$, in the following sense. We seek two gray levels $g_0$ and $g_1$, and the map $g\colon E\to\{g_0, g_1\}$ minimizing the distance

\begin{equation}
d(f, g)=\| f-g\|_2^2=\label{eq:1}\sum_{x\in E}\left(f(x)-g(x)\right)^{2}.
\end{equation}

At this point, it should be noted that the above choice of distance will result in $g$ being the maximum likelihood estimator of $f$ in the presence of Gaussian noise (a common assumption in image analysis -- even if noise rather follows a Poisson distribution on real detectors).

It can readily be verified that the above optimization problem in fact reduces to Otsu's method! To prove this assertion, we need to rewrite this problem. Let $g$ be the solution to Problem \eqref{eq:1}. Then, for all $x, y\in E$

\begin{align}
\label{eq:2}f(x) = f(y)\quad & \Rightarrow\quad g(x)=g(y),\\
\label{eq:8}f(x) < f(y)\quad & \Rightarrow\quad g(x) \leq g(y).
\end{align}

The proof of the above assertions can be found in the appendix (see XXXX and YYY).
 Similarly, we have, for all $x, y\in E$

\begin{equation}

\end{equation}


Therefore, the optimum binary function $g$ has the following form

\begin{equation}
\label{eq:7}g(x)=\Phi(f(x)),
\end{equation}

where $\Phi\colon\{0,\ldots,L-1\}\to\{g_0, g_1\}$ is a non-decreasing function which maps any grey level of the original image onto one of the two values of $g$. Since $\Phi$ can take only two values, it is

* Appendix

** Proof of assertion \eqref{eq:2}

This assertion is proved by contradiction. Let us assume that there exists two pixels $x$ and $y$ ($x\neq y$) with same value in the original image ($f(x)=f(y)$) and different values in the binary approximation ($g(x)\neq g(y)$). We select $g_2\in\{g(x),g(y)\}=\{g_0, g_1\}$ so that

\begin{equation}
\label{eq:3}\left(f(x)-g_2\right)^2=\left(f(y)-g_2\right)^2=\min\left(\left(f(x)-g(x)\right)^2, \left(f(y)-g(y)\right)^2\right),
\end{equation}

and

\begin{equation}
\label{eq:4}\left(f(x)-g_2\right)^2+\left(f(y)-g_2\right)^2<\left(f(x)-g(x)\right)^2+\left(f(y)-g(y)\right)^2,
\end{equation}
since $g(x)\neq g(y)$. It should be noted that the above inequality is /strict/. We then define $\tilde g\colon E\to\{g_0,g_1\}$ so that

\begin{equation}
\label{eq:5}\tilde g(z)=
\begin{cases}
g_2 & \text{if }z=x\text{ or }z=y,\\
g(z) & \text{otherwise}.
\end{cases}
\end{equation}

Then, simple algebra leads to

\begin{equation}
\label{eq:6}d(f,\tilde g)^2-d(f,g)^2=\left(f(x)-g_2\right)^2+\left(f(y)-g_2\right)^2-\left(f(x)-g(x)\right)^2-\left(f(y)-g(y)\right)^2.
\end{equation}


From Eq. \eqref{eq:4}], we then find $d(f,\tilde g)^2 < d(f,g)^2$, which leads to a contradiction, since $g$ optimizes the distance to $f$.Thus, assertion \eqref{eq:2} is proved.

** Proof of assertion \eqref{eq:8}

This assertion is again proved by contradiction. Let us assume that there exists $x, y\in E$ such that $f(x) < f(y)$ and $g(x) > g(y)$. Then, simple algebra shows that

\begin{equation}
\label{eq:9}\left[f(x)-g(y)\right]^2+\left[f(y)-g(x)\right]^2=\left[f(x)-g(x)\right]^2+\left[f(y)-g(y)\right]^2+2\left[f(y)-f(x)\right]\left[g(y)-g(x)\right],
\end{equation}
and the last term is negative. Proceeding as above, we then build $\tilde g$ as follows
\begin{equation}
\label{eq:10}\tilde g(z)=
\begin{cases}
g(y) & \text{if }z=x,\\
g(x) & \text{if }z=y,\\
g(z) & \text{otherwise}.
\end{cases}
\end{equation}

Then
\begin{equation}
\label{eq:11}d(f, \tilde g)^2-d(f,g)^2=
\end{equation}

with $\| f-\tilde g\|_2^2<\| f-g\|_2^2$, which leads to a contradiction.
