# -*- coding: utf-8; -*-
#+TITLE: The periodic Green operator for strains
#+SETUPFILE: "../../header.org"
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../../solarized.css" />

The Green operator for strains is defined as the linear operator which maps --in a homogeneous material-- the local prestress to the (opposite of the) local strain. Closed-form expressions of this operator can be derived in the case of periodic boundary conditions, as will be demonstrated in the present post.@@html:<!-- more -->@@

Let $\stiffness$ be the stiffness of a homogeneous, linearly elastic material occupying the whole, $d$-dimensional, space $\reals^d$. This material is submitted to the local, $(L_1,\cdots,L_d)$-periodic prestress $\prestress(\vec x)$. The elastic equilibrium of this medium is governed by the following equations over $\reals^d$

\begin{align}
\label{eq:1}
\nabla_\vec x\cdot\stress&=\vec0 & (\vec x\in\reals^d)\\
\label{eq:2}
\stress(\vec x)&=\stiffness:\strain(\vec x)+\prestress(\vec x)&(\vec x\in\reals^d)\\
\label{eq:3}
\strain(\vec x)&=\nabla_\vec x^\text s\displ&(\vec x\in\reals^d)\\
\label{eq:4}
\displ(\vec x+L_i\vec e_i)&=\displ(\vec x)&(\vec x\in\reals^d)\\
\label{eq:5}
\stress(\vec x+L_i\vec e_i)\cdot\vec e_i&=\stress(\vec x)\cdot\vec e_i&(\vec x\in\reals^d)
\end{align}

It should be noted that in Eqs. \eqref{eq:4} and \eqref{eq:5}, no summation should be carried out on the repeated index $i$. This problem is conveniently solved in Fourier space. Indeed, since the local displacement $\displ$ is periodic, it can be decomposed in a Fourier series

\begin{equation*}
\displ(\vec x)=\sum_{b\in\integers^d}\hat\displ_b\exp(\imath\vec k_b\cdot\vec x),
\end{equation*}

with

\begin{equation*}
\vec k_b=\frac{2\pi b_1}{L_1}\vec e_1+\cdots+\frac{2\pi b_d}{L_d}\vec e_d,
\end{equation*}

and

\begin{equation*}
\hat\displ_b=\frac1{\meas{\domain}}\int_\domain\displ(\vec x)\exp(-\imath\vec k_b\cdot\vec x)\dV{\vec x},
\end{equation*}

where $b=(b_1,\ldots,b_d)\in\integers^d$ is a multi-index, and $\domain=(0,L_1)\times\cdots\times(0,L_d)$ denotes the unit-cell.
