# -*- coding: utf-8; -*-
#+SETUPFILE: "./include/css-0.org
#+TITLE: Welcome!

You've reached the blog of Sébastien Brisard (follow the [[file:./pages/about.org][About me]] link for a brief CV). My most recent posts are listed below. A full list of posts can be found in the [[file:./posts/archives.org][Archives]] page. These posts frequently refer to work published by myself or others; the full bibliographic references are provided in the [[file:./pages/references.org][References]] page.

* [[file:posts/20151208-New_paper_published.org][2015-12-08 -- New paper published]]

My student Vinh Phuc Tran has recently had one of his paper published in /Mechanics of Materials/. The paper is called /Stochastic modeling of mesoscopic elasticity random field/.

* [[file:./posts/20150930-Orientation_correlations_among_rice_grains-06.org][2015-09-30 -- Orientation correlations among rice grains, part 6: segmentation]]

In the [[file:./posts/20150709-Orientation_correlations_among_rice_grains-05.org][previous instalment]] of this series, I showed that a convincing binary image could be produced from the gray level 3D reconstruction of the assembly of rice grains, using Otsu's threshold. However, I intend to carry out statistical analyses of the /grains/ themselves in the subsequent instalments. Therefore, instead of a binary image of the rice grains, what is really needed is a /labelled/ image, where all voxels which are thought to belong to the same rice grain are tagged with the same label. This is called /segmentation/, which is the topic of the present post. I will first show that the most basic segmentation technique (namely, detecting connected components in the image) fails in the present case. This calls for a more elaborate strategy, based on the widely popular [[https://en.wikipedia.org/wiki/Watershed_%28image_processing%29][watershed]] method. However, blind application of the standard watershed strategy leads to over-segmentation. This post will therefore close on a problem-dependent strategy better suited to the present case.

* [[file:./posts/20150709-Orientation_correlations_among_rice_grains-05.org][2015-07-09 -- Orientation correlations among rice grains, part 5: thresholding]]

In the [[file:./posts/20150529-Orientation_correlations_among_rice_grains-04.org][previous instalment]] of this series, we used the circle Hough transform to find the boundary of the sample and define the circular ROI. Within this ROI, we now need to segment the rice grains. In other words, starting from a gray-level image (Fig. 1, left), we want to produce a binary image, where all pixels that we believe belong to rice grains are white, and all background pixels are black (Fig. 1, right). This is the topic of the present post, where we will use Otsu's automated threshold selection. I will first discuss Otsu's method, and propose what I believe is a new interpretation of this rather old technique. Then, I will apply this method to the 3D image of rice grains, using [[http://scikit-image.org/][scikit-image]].

* [[file:./posts/20150706-When_a_thin_shell_is_not_so_thin-03.org][2015-07-06 -- When a thin shell is not so thin, part\nbsp{}3: the thick shell solution]]

Finding the stress resultant and stress couple in a spherical pressure vessel seems easy enough. Well, this apparently simple problem allows us to highlight subtle thickness effects within shells. It should be emphasized again that these thickness effects have nothing to do with shear corrections. Indeed, shear stresses are null at any point of the spherical pressure vessel. Rather, the thickness effects we are discussing in this series are due to curvature.

In the [[file:./posts/20150608-When_a_thin_shell_is_not_so_thin-01.org][first instalment]] of this series, I showed that using Koiter's thin shell solution leads to a non-null stress couple, which came as quite a surprise. In the [[file:./posts/20150701-When_a_thin_shell_is_not_so_thin-02.org][second instalment]], I used the exact, 3D solution to derive reference values of the stress couple and stress resultant through integration over the thickness of the shell. In particular, I showed that thickness corrections /had/ to be incorporated.

This still does not settle the matter, since the results obtained within the framework of Koiter's thin shell theory (see [[file:./posts/20150608-When_a_thin_shell_is_not_so_thin-01.org][first instalment]]) are inconsistent with the reference, 3D elasticity values (see [[file:./posts/20150701-When_a_thin_shell_is_not_so_thin-02.org][second instalment]]). To reconcile both approaches (3D elasticity vs. shell theory), we need to use a /thick/ shell theory, as illustrated below.

* [[file:./posts/20150701-When_a_thin_shell_is_not_so_thin-02.org][2015-07-01 -- When a thin shell is not so thin, part\nbsp{}2: the 3D, exact solution]]

In the [[file:./posts/20150608-When_a_thin_shell_is_not_so_thin-01.org][previous instalment]] of this series, we analysed a spherical pressure vessel by means of Koiter's linear theory of thin shells. We found the somewhat unexpected result that the stress couple was not null. Besides, we also found that the stress resultant was slightly different from the well-known value N=pR/2. So what was wrong with the previous analysis? To explore this question, we will make use of the exact solution in 3D elasticity.

* [[file:./posts/20150701-This_blog_is_now_licensed.org][2015-07-01 -- This blog is now licensed!]]

As indicated at the bottom of each page of this website, this blog is now licensed under a [[http://creativecommons.org/licenses/by-nc/4.0/][Creative Commons Attribution-NonCommercial 4.0 International License]]. This means that you are free to share and/or adapt the contents of this blog, as long as you give appropriate credit to the author. You may not make profit out of this website, though.

* [[file:./posts/20150608-When_a_thin_shell_is_not_so_thin-01.org][2015-06-08 -- When a thin shell is not so thin, part\nbsp{}1: Koiter's linear theory]]

In structural analysis, thick beams (resp. plates) usually refer to shear deformability, and the [[http://en.wikipedia.org/wiki/Timoshenko_beam_theory][Timoshenko beam theory]] (resp. [[http://en.wikipedia.org/wiki/Mindlin%E2%80%93Reissner_plate_theory][Mindlin–Reissner plate theory]]). With curved elements however (e.g. curved beams or shells), the situation is more subtle, as thickness corrections may be necessary even in shells /where the shear stress is null at any point/. In this series, this is illustrated with a spherical pressure vessel, for which the stress resultants and couples are studied. "Easy enough", you probably think: N=pR/2, M=0 and that's the end of it ([[http://en.wikipedia.org/wiki/Pressure_vessel#Stress_in_thin-walled_pressure_vessels][Wikipedia]]). Well, maybe...

* [[file:./posts/20150529-Orientation_correlations_among_rice_grains-04.org][2015-05-29 -- Orientation correlations among rice grains, part 4: defining the ROI]]

In the [[file:./posts/20150330-Orientation_correlations_among_rice_grains-03.org][previous instalment]] of this series, we obtained binned slices of the sample. Fig. 1 is a typical example of these binned slices. We now want to segment the rice grains. However, the analysis (in particular, Otsu thresholding) might be perturbed by the fact that the walls of the sample container are visible on the 3D image. In this post, I will show how we can locate these walls. Then, any subsequent analysis will be performed within the Region Of Interest (ROI) thus defined.

* [[file:./posts/20150330-Orientation_correlations_among_rice_grains-03.org][2015-03-30 -- Orientation correlations among rice grains, part 3: intermezzo -- Binning images]]

The full reconstructed image resulting from the tomography experiment described in the [[file:./posts/20150310-Orientation_correlations_among_rice_grains-02.org][second]] instalment of this series is a 1747×1751×688 stack. The voxel size is about 0.030 mm. This is far too much for the purpose of the present study, since all we are interested in is the determination of the location (coordinates of the centroid) and orientation (principal axes of inertia) of the rice grains. In order to reduce the computation time, the images will first be /binned/, that is each set of (say) 4×4×4 voxels will be replaced with a unique voxel, with average gray value. 3D binning would usually require three uggly nested loops. There is, however, a much more pythonic way. This is the topic of the present post.

* [[file:./posts/20150310-Orientation_correlations_among_rice_grains-02.org][2015-03-10 -- Orientation correlations among rice grains, part 2: acquisition of tomography images]]

In the [[file:./posts/20150223-Orientation_correlations_among_rice_grains-01.org][first]] instalment of this series, I briefly introduced orientational order in assemblies of anisotropic particles, and proposed an illustration based on synthetic microstructures. But what I really intend to do in this series is to show how orientational order can be quantified in a "real-life" sample, namely a packing of rice grains. This of course requires a 3D image of the packing. Fortunately, my lab ([[http://navier.enpc.fr/][Laboratoire Navier]]) is the proud host of a [[http://navier.enpc.fr/Microtomographe,297][collaborative microtomography platform]] and my former colleague Nicolas Lenoir --who was in charge of this instrument-- gave me the opportunity to scan my toy sample in december 2013.

* [[file:./posts/20150223-Orientation_correlations_among_rice_grains-01.org][2015-02-23 -- Orientation correlations among rice grains, part 1: introduction]]

In this series, I will explore the notion of orientational order in random packings of anisotropic (flat or elongated), hard particles. By orientational order, I mean that particles which are close to each other tend to adopt the same orientation. This leads to strong /local/ anisotropy, while the packing may well be /globally/ isotropic; in particular, all orientations of single grains are equiprobable. Local orientational order is stronger when the volume fraction of particles, or their aspect ratio increases.

* [[file:./posts/20141219-New_Blog.org][2014-12-19 -- New Blog!]]

My blog was previously hosted by Blogger. I have now moved to [[https://pages.github.com/][GitHub Pages]], and a statically generated blog. This new website is entirely generated with Emacs' [[http://orgmode.org/][Org mode]] (the source files of my blog can be found [[https://github.com/sbrisard/blog][here]]; see in particular the [[https://github.com/sbrisard/blog/blob/master/sb-blog.el][config file]]). The stylesheet is inspired by the [[http://orgmode.org/worg/][Hello Worg]] website, the simplicity of which I like. It is a rather exciting experience for me to build a whole website "from scratch". Of course, there are many things I need to learn, and this blog should hopefully improve with time... be patient! Meanwhile, have a look to my previous posts which I have ported to this site. Happy reading!

* [[file:./posts/20140813-Review_of_Parallel_Programming_with_Python.org][2014-08-13 -- Review of "Parallel Programming with Python"]]

I have again recently been offered by [[http://www.packtpub.com/][Packt Publishing]] to review one of their books, entitled [[http://goo.gl/oMUSLW][Parallel Programming with Python]] (by Jan Palach).

* [[file:./posts/20140306-The_periodic_Green_operator_for_strains.org][2014-03-06 -- The periodic Green operator for strains]]

The Green operator for strains is defined as the linear operator which maps --in a homogeneous material-- the local prestress to the (opposite of the) local strain. Closed-form expressions of this operator can be derived in the case of periodic boundary conditions, as will be demonstrated in the present post.

* [[file:./posts/20140226-Decomposition_of_transverse_isotropic_fourth-rank_tensors.org][2014-02-26 -- Decomposition of transverse isotropic, fourth-rank tensors]]

In [[file:./posts/20140112-Elastic_constants_of_an_isotropic_material-03.org][a previous post]], I introduced the fourth-rank spherical and deviatoric projection tensors. Any isotropic fourth-rank tensor is a linear combination of these two tensors; in other words, the space of isotropic fourth-rank tensors (with minor and major symmetries) is of dimension 2. Similarly, it can be shown ([[file:./pages/references.org::#WALP1984][Walpole, 1984]]) that the space of three-dimensional, /transverse isotropic/ fourth-rank tensors (with minor and major symmetries) is of dimension 6. Furthermore; it is possible to produce a convenient basis of this space. This is the topic of the present post, which is mostly based on the paper by Walpole ([[file:./pages/references.org::#WALP1984][1984]]).

* [[file:./posts/20140219-On_the_double_dot_product.org][2014-02-19 -- On the double dot product]]

The double dot product of two tensors is the contraction of these tensors with respect to the last two indices of the first one, and the first two indices of the second one. Whether or not this contraction is performed on the /closest/ indices is a matter of convention. In this post, I will show that this choice has some important implications.

* [[file:./posts/20140131-The_elastic_acoustic_tensor_and_its_inverse.org][2014-01-31 -- The elastic acoustic tensor and its inverse]]

In this post, I will introduce the acoustic tensor of linearly elastic materials. Closed-form expressions of the inverse of this tensor can be derived in the case of /isotropic/ materials. This will later come in handy to derive closed-form expressions of the periodic Green operator for strains.
