# -*- coding: utf-8; -*-
#+TITLE: Welcome!

You've reached the blog of Sébastien Brisard (follow the [[file:./pages/about.org][About me]] link for a brief CV). My most recent posts are listed below. A full list of posts can be found in the [[file:./posts/archives.org][Archives]] page. These posts frequently refer to work published by myself or others; the full bibliographic references are provided in the [[file:./pages/references.org][References]] page.

* [[file:./posts/201412XX-New_Blog.org][2014-12-17 -- New Blog!]]

My blog was previously hosted by Blogger. I have now moved to [[https://pages.github.com/][GitHub Pages]], and a statically generated blog. This new website is entirely generated with Emacs' [[http://orgmode.org/][Org mode]] (the source files of my blog can be found [[https://github.com/sbrisard/blog][here]]; see in particular the [[https://github.com/sbrisard/blog/blob/master/init.el][config file]]). The stylesheet is inspired by the [[http://orgmode.org/worg/][Hello Worg]] website, whose simplicity I like. It is a rather exciting experience for me to build a whole website "from scratch". Of course, there are many things I need to learn, and this blog should hopefully improve with time... be patient! Meanwhile, have a look to my previous posts which I have ported to this site. Happy reading!

* [[file:./posts/20140813-Review_of_Parallel_Programming_with_Python.org][2014-08-13 -- Review of "Parallel Programming with Python"]]

I have again recently been offered by [[http://www.packtpub.com/][Packt Publishing]] to review one of their books, entitled [[http://goo.gl/oMUSLW][Parallel Programming with Python]] (by Jan Palach).

* [[file:./posts/20140306-The_periodic_Green_operator_for_strains.org][2014-03-06 -- The periodic Green operator for strains]]

The Green operator for strains is defined as the linear operator which maps --in a homogeneous material-- the local prestress to the (opposite of the) local strain. Closed-form expressions of this operator can be derived in the case of periodic boundary conditions, as will be demonstrated in the present post.

* [[file:./posts/20140226-Decomposition_of_transverse_isotropic_fourth-rank_tensors.org][2014-02-26 -- Decomposition of transverse isotropic, fourth-rank tensors]]

In [[file:./posts/20140112-Elastic_constants_of_an_isotropic_material-03.org][a previous post]], I introduced the fourth-rank spherical and deviatoric projection tensors. Any isotropic fourth-rank tensor is a linear combination of these two tensors; in other words, the space of isotropic fourth-rank tensors (with minor and major symmetries) is of dimension 2. Similarly, it can be shown ([[file:./pages/references.org::#WALP1984][Walpole, 1984]]) that the space of three-dimensional, /transverse isotropic/ fourth-rank tensors (with minor and major symmetries) is of dimension 6. Furthermore; it is possible to produce a convenient basis of this space. This is the topic of the present post, which is mostly based on the paper by Walpole ([[file:./pages/references.org::#WALP1984][1984]]).

* [[file:./posts/20140219-On_the_double_dot_product.org][2014-02-19 -- On the double dot product]]

The double dot product of two tensors is the contraction of these tensors with respect to the last two indices of the first one, and the first two indices of the second one. Whether or not this contraction is performed on the /closest/ indices is a matter of convention. In this post, I will show that this choice has some important implications.

* [[file:./posts/20140131-The_elastic_acoustic_tensor_and_its_inverse.org][2014-01-31 -- The elastic acoustic tensor and its inverse]]

In this post, I will introduce the acoustic tensor of linearly elastic materials. Closed-form expressions of the inverse of this tensor can be derived in the case of /isotropic/ materials. This will later come in handy to derive closed-form expressions of the periodic Green operator for strains.
